-- Re-seed site_settings (safe: ON CONFLICT DO NOTHING)
INSERT INTO site_settings (id, setting_key, setting_value, setting_group, is_public, description, created_at, updated_at)
VALUES
  (gen_random_uuid(), 'site_name',             'BigBike',                                        'general',       true,  'Ten website hien thi header/footer.',              now(), now()),
  (gen_random_uuid(), 'footer_tagline',        'BIGBIKE MONG DUOC LANG NGHE VA THAU HIEU BAN HON','general',      true,  'Slogan footer.',                                   now(), now()),
  (gen_random_uuid(), 'footer_description',    'BigBike chuyen cung cap gear moto chinh hang.',   'general',      true,  'Mo ta ngan o footer.',                             now(), now()),
  (gen_random_uuid(), 'bct_url',               'https://online.gov.vn',                           'general',      true,  'URL dang ky Bo Cong Thuong.',                      now(), now()),
  (gen_random_uuid(), 'hotline',               '0906.90.2404',                                    'contact',      true,  'Hotline chinh.',                                   now(), now()),
  (gen_random_uuid(), 'hotline_2',             '0764.640.679',                                    'contact',      true,  'Hotline phu.',                                     now(), now()),
  (gen_random_uuid(), 'contact_email',         'info@bigbike.vn',                                 'contact',      true,  'Email lien he cong khai.',                         now(), now()),
  (gen_random_uuid(), 'contact_address',       '79/30/52 Au Co, Phuong 14, Quan 11, TP.HCM',      'contact',      true,  'Dia chi cua hang.',                                now(), now()),
  (gen_random_uuid(), 'facebook_url',          'https://www.facebook.com/bigbikegear',            'contact',      true,  'Link Facebook.',                                   now(), now()),
  (gen_random_uuid(), 'zalo_url',              'https://zalo.me/bigbikegear',                     'contact',      true,  'Link Zalo.',                                       now(), now()),
  (gen_random_uuid(), 'messenger_url',         'https://m.me/bigbikegear',                        'contact',      true,  'Facebook Messenger deep link.',                    now(), now()),
  (gen_random_uuid(), 'google_maps_url',       '',                                                'contact',      true,  'URL nhung Google Maps trang Lien he.',              now(), now()),
  (gen_random_uuid(), 'promo_title',           'LS2 DUAL SPORT MX436 PIONEER',                   'public_home',  true,  'Tieu de banner khuyen mai trang chu.',              now(), now()),
  (gen_random_uuid(), 'promo_off',             '20% OFF',                                         'public_home',  true,  'Nhan % giam tren banner.',                         now(), now()),
  (gen_random_uuid(), 'promo_href',            '/san-pham',                                       'public_home',  true,  'URL khi click banner khuyen mai.',                 now(), now()),
  (gen_random_uuid(), 'promo_image_url',       '',                                                'public_home',  true,  'Anh banner khuyen mai.',                           now(), now()),
  (gen_random_uuid(), 'home_exp_subtitle',     'GOC TRAI NGHIEM CUNG BIGBIKE',                   'public_home',  true,  'Khu trai nghiem - kicker.',                        now(), now()),
  (gen_random_uuid(), 'home_exp_title',        'PHU KIEN DI PHUOT MOTO CAO CAP',                 'public_home',  true,  'Khu trai nghiem - tieu de.',                       now(), now()),
  (gen_random_uuid(), 'home_exp_desc',         'Tai shop ban do phuot moto Bigbike, cac san pham do bao ho moto va phu kien phuot rat da dang.', 'public_home', true, 'Khu trai nghiem - mo ta.', now(), now()),
  (gen_random_uuid(), 'seo_home_title',        'BigBike - Do bao ho moto chinh hang',             'seo',          true,  'SEO Title trang chu.',                             now(), now()),
  (gen_random_uuid(), 'seo_home_description',  'BigBike - shop do bao ho moto uy tin tai TP.HCM.','seo',          true,  'SEO Description trang chu.',                       now(), now()),
  (gen_random_uuid(), 'og_image_url',          '',                                                'seo',          true,  'Anh share Facebook (Open Graph).',                 now(), now()),
  (gen_random_uuid(), 'seo_home_h1',           '',                                                'seo',          true,  'Tieu de H1 trang chu.',                            now(), now()),
  (gen_random_uuid(), 'store_currency',        'VND',                                             'store',        true,  'Don vi tien te.',                                  now(), now()),
  (gen_random_uuid(), 'store_timezone',        'Asia/Ho_Chi_Minh',                                'store',        false, 'Timezone he thong.',                               now(), now()),
  (gen_random_uuid(), 'order_min_amount',      '0',                                               'store',        false, 'Don toi thieu de checkout (VND).',                 now(), now()),
  (gen_random_uuid(), 'low_stock_threshold',   '5',                                               'store',        false, 'Nguong canh bao sap het hang.',                    now(), now()),
  (gen_random_uuid(), 'tax_enabled',           'false',                                           'tax',          false, 'Bat tinh thue tu dong.',                           now(), now()),
  (gen_random_uuid(), 'tax_rate',              '0.10',                                            'tax',          false, 'Thue suat VAT (0.10 = 10%).',                      now(), now()),
  (gen_random_uuid(), 'tax_inclusive',         'false',                                           'tax',          false, 'Gia da bao gom thue.',                             now(), now()),
  (gen_random_uuid(), 'tax_label',             'VAT',                                             'tax',          true,  'Nhan thue tren hoa don.',                          now(), now()),
  (gen_random_uuid(), 'tax_registration_number','',                                               'tax',          false, 'Ma so thue (MST).',                                now(), now()),
  (gen_random_uuid(), 'login_max_attempts',    '5',                                               'security',     false, 'So lan dang nhap sai toi da.',                     now(), now()),
  (gen_random_uuid(), 'session_timeout_minutes','60',                                             'security',     false, 'Timeout phien admin (phut).',                      now(), now()),
  (gen_random_uuid(), 'payment_sepay.enabled',        'false',    'payment_sepay', false, 'Bat/tat cong thanh toan SePay.',            now(), now()),
  (gen_random_uuid(), 'payment_sepay.webhook_token',  '',         'payment_sepay', false, 'Token bi mat SePay webhook.',               now(), now()),
  (gen_random_uuid(), 'payment_sepay.bank_name',      '',         'payment_sepay', true,  'Ten ngan hang (vd: MB Bank).',              now(), now()),
  (gen_random_uuid(), 'payment_sepay.bank_bin',       '',         'payment_sepay', true,  'BIN ngan hang VietQR (vd: 970422).',        now(), now()),
  (gen_random_uuid(), 'payment_sepay.account_number', '',         'payment_sepay', true,  'So tai khoan nhan tien.',                   now(), now()),
  (gen_random_uuid(), 'payment_sepay.account_holder', '',         'payment_sepay', true,  'Ten chu tai khoan (in hoa).',               now(), now()),
  (gen_random_uuid(), 'payment_sepay.timeout_hours',  '48',       'payment_sepay', false, 'So gio cho thanh toan truoc khi huy don.',  now(), now()),
  (gen_random_uuid(), 'payment_sepay.qr_template',    'compact2', 'payment_sepay', false, 'Template QR VietQR.',                       now(), now())
ON CONFLICT (setting_key) DO NOTHING;

SELECT setting_group, COUNT(*) as count FROM site_settings GROUP BY setting_group ORDER BY setting_group;
