-- V133: Product installation guide (rich HTML) + product FAQ list.
-- Backs the rebuilt PDP layout: section "03 Hướng dẫn lắp đặt" and "05 Câu hỏi thường gặp".
-- installation_guide mirrors the promotion_content / content_bottom rich-text pattern;
-- product_faqs mirrors the product_specifications child-table pattern.

alter table products
    add column installation_guide text;

create table product_faqs (
    id bigint generated by default as identity primary key,
    product_id varchar(64) not null,
    sort_order integer not null,
    question varchar(500) not null,
    answer text not null,
    constraint fk_product_faqs_product_id
        foreign key (product_id) references products (id) on delete cascade
);

create index if not exists idx_product_faqs_product_id on product_faqs (product_id);
