-- V175: Product SEO template fields (xem SEO_PDP_IMPLEMENTATION_PLAN.md, Giai đoạn 3).
-- Bổ sung: bảng con product_highlights (Ưu/Nhược điểm), cột scalar bảo hành/xuất xứ/
-- bảng size trên products, và cột description trên product_videos. Trọng lượng dùng lại
-- cột weight_kg đã có (không thêm cột).

-- Ưu điểm / Nhược điểm — schema.org positiveNotes/negativeNotes. Một bảng con phân biệt
-- bằng kind, mirror product_faqs. Song ngữ inline (content / content_en).
create table product_highlights (
    id bigint generated by default as identity primary key,
    product_id varchar(64) not null,
    kind varchar(8) not null,
    sort_order integer not null,
    content text not null,
    content_en text,
    constraint fk_product_highlights_product_id
        foreign key (product_id) references products (id) on delete cascade,
    constraint ck_product_highlights_kind
        check (kind in ('PRO', 'CON'))
);

create index if not exists idx_product_highlights_product_id on product_highlights (product_id);

-- Cột scalar mới trên products: bảo hành, xuất xứ, bảng size.
alter table products
    add column warranty_months            integer,
    add column warranty_scope             text,
    add column origin_brand_country       varchar(120),
    add column origin_manufacture_country varchar(120),
    add column size_guide                 text;

-- Mô tả video (1 ngôn ngữ) cho VideoObject schema + caption dưới embed.
alter table product_videos
    add column description text;
