create table brands (
    id varchar(64) primary key,
    slug varchar(160) not null unique,
    name varchar(255) not null,
    description text,
    logo_id varchar(64),
    logo_url text,
    logo_alt varchar(255),
    logo_width integer,
    logo_height integer,
    logo_mime_type varchar(100),
    seo_title varchar(255),
    seo_description text,
    seo_canonical_url text,
    seo_og_image_id varchar(64),
    seo_og_image_url text,
    seo_og_image_alt varchar(255),
    seo_og_image_width integer,
    seo_og_image_height integer,
    seo_og_image_mime_type varchar(100),
    seo_no_index boolean,
    is_visible boolean not null,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null
);

create table categories (
    id varchar(64) primary key,
    slug varchar(160) not null unique,
    name varchar(255) not null,
    description text,
    parent_id varchar(64),
    image_id varchar(64),
    image_url text,
    image_alt varchar(255),
    image_width integer,
    image_height integer,
    image_mime_type varchar(100),
    icon_id varchar(64),
    icon_url text,
    icon_alt varchar(255),
    icon_width integer,
    icon_height integer,
    icon_mime_type varchar(100),
    seo_title varchar(255),
    seo_description text,
    seo_canonical_url text,
    seo_og_image_id varchar(64),
    seo_og_image_url text,
    seo_og_image_alt varchar(255),
    seo_og_image_width integer,
    seo_og_image_height integer,
    seo_og_image_mime_type varchar(100),
    seo_no_index boolean,
    is_visible boolean not null,
    sort_order integer,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_categories_parent_id
        foreign key (parent_id) references categories (id)
);

create table products (
    id varchar(64) primary key,
    sku varchar(100),
    slug varchar(200) not null unique,
    name varchar(255) not null,
    short_description text,
    description text,
    brand_id varchar(64),
    category_id varchar(64) not null,
    image_id varchar(64),
    image_url text,
    image_alt varchar(255),
    image_width integer,
    image_height integer,
    image_mime_type varchar(100),
    retail_price integer not null,
    compare_at_price integer,
    sale_price integer,
    currency varchar(8) not null,
    stock_state varchar(32) not null,
    publish_status varchar(32) not null,
    is_featured boolean,
    show_on_homepage boolean,
    seo_title varchar(255),
    seo_description text,
    seo_canonical_url text,
    seo_og_image_id varchar(64),
    seo_og_image_url text,
    seo_og_image_alt varchar(255),
    seo_og_image_width integer,
    seo_og_image_height integer,
    seo_og_image_mime_type varchar(100),
    seo_no_index boolean,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_products_brand_id
        foreign key (brand_id) references brands (id),
    constraint fk_products_category_id
        foreign key (category_id) references categories (id),
    constraint ck_products_publish_status
        check (publish_status in ('DRAFT', 'PUBLISHED', 'HIDDEN', 'ARCHIVED')),
    constraint ck_products_stock_state
        check (stock_state in ('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK', 'PREORDER', 'CONTACT_FOR_STOCK')),
    constraint ck_products_currency
        check (currency = 'VND')
);

create table product_category_map (
    product_id varchar(64) not null,
    category_id varchar(64) not null,
    primary key (product_id, category_id),
    constraint fk_product_category_map_product_id
        foreign key (product_id) references products (id) on delete cascade,
    constraint fk_product_category_map_category_id
        foreign key (category_id) references categories (id)
);

create table product_gallery_images (
    id bigint generated by default as identity primary key,
    product_id varchar(64) not null,
    sort_order integer not null,
    image_id varchar(64),
    image_url text not null,
    image_alt varchar(255),
    image_width integer,
    image_height integer,
    image_mime_type varchar(100),
    constraint fk_product_gallery_images_product_id
        foreign key (product_id) references products (id) on delete cascade
);

create table product_videos (
    id bigint generated by default as identity primary key,
    product_id varchar(64) not null,
    sort_order integer not null,
    video_id varchar(64),
    video_url text not null,
    title varchar(255),
    provider varchar(32),
    thumbnail_id varchar(64),
    thumbnail_url text,
    thumbnail_alt varchar(255),
    thumbnail_width integer,
    thumbnail_height integer,
    thumbnail_mime_type varchar(100),
    constraint fk_product_videos_product_id
        foreign key (product_id) references products (id) on delete cascade
);

create table product_specifications (
    id bigint generated by default as identity primary key,
    product_id varchar(64) not null,
    sort_order integer not null,
    name varchar(255) not null,
    spec_value text not null,
    group_name varchar(255),
    constraint fk_product_specifications_product_id
        foreign key (product_id) references products (id) on delete cascade
);

create table product_variants (
    id varchar(64) primary key,
    product_id varchar(64) not null,
    sku varchar(100),
    name varchar(255) not null,
    retail_price integer,
    compare_at_price integer,
    sale_price integer,
    currency varchar(8),
    stock_state varchar(32) not null,
    image_id varchar(64),
    image_url text,
    image_alt varchar(255),
    image_width integer,
    image_height integer,
    image_mime_type varchar(100),
    is_available boolean not null,
    sort_order integer not null,
    constraint fk_product_variants_product_id
        foreign key (product_id) references products (id) on delete cascade,
    constraint ck_product_variants_stock_state
        check (stock_state in ('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK', 'PREORDER', 'CONTACT_FOR_STOCK')),
    constraint ck_product_variants_currency
        check (currency is null or currency = 'VND')
);

create table product_variant_options (
    id bigint generated by default as identity primary key,
    variant_id varchar(64) not null,
    sort_order integer not null,
    option_name varchar(255) not null,
    option_value varchar(255) not null,
    constraint fk_product_variant_options_variant_id
        foreign key (variant_id) references product_variants (id) on delete cascade
);

create table content_categories (
    id varchar(64) primary key,
    slug varchar(160) not null unique,
    name varchar(255) not null
);

create table content_authors (
    id varchar(64) primary key,
    name varchar(255) not null
);

create table articles (
    id varchar(64) primary key,
    slug varchar(200) not null unique,
    title varchar(255) not null,
    excerpt text,
    body text not null,
    cover_image_id varchar(64),
    cover_image_url text,
    cover_image_alt varchar(255),
    cover_image_width integer,
    cover_image_height integer,
    cover_image_mime_type varchar(100),
    author_id varchar(64),
    category_id varchar(64),
    publish_status varchar(32) not null,
    seo_title varchar(255),
    seo_description text,
    seo_canonical_url text,
    seo_og_image_id varchar(64),
    seo_og_image_url text,
    seo_og_image_alt varchar(255),
    seo_og_image_width integer,
    seo_og_image_height integer,
    seo_og_image_mime_type varchar(100),
    seo_no_index boolean,
    published_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint fk_articles_author_id
        foreign key (author_id) references content_authors (id),
    constraint fk_articles_category_id
        foreign key (category_id) references content_categories (id),
    constraint ck_articles_publish_status
        check (publish_status in ('DRAFT', 'PUBLISHED', 'HIDDEN', 'ARCHIVED'))
);

create table article_tags (
    article_id varchar(64) not null,
    sort_order integer not null,
    tag varchar(120) not null,
    primary key (article_id, sort_order),
    constraint fk_article_tags_article_id
        foreign key (article_id) references articles (id) on delete cascade
);

create table pages (
    id varchar(64) primary key,
    slug varchar(200) not null unique,
    title varchar(255) not null,
    body text not null,
    page_type varchar(32) not null,
    publish_status varchar(32) not null,
    seo_title varchar(255),
    seo_description text,
    seo_canonical_url text,
    seo_og_image_id varchar(64),
    seo_og_image_url text,
    seo_og_image_alt varchar(255),
    seo_og_image_width integer,
    seo_og_image_height integer,
    seo_og_image_mime_type varchar(100),
    seo_no_index boolean,
    published_at timestamp with time zone,
    created_at timestamp with time zone not null,
    updated_at timestamp with time zone not null,
    constraint ck_pages_page_type
        check (page_type in ('ABOUT', 'CONTACT', 'POLICY', 'HELP', 'CUSTOM')),
    constraint ck_pages_publish_status
        check (publish_status in ('DRAFT', 'PUBLISHED', 'HIDDEN', 'ARCHIVED'))
);

create index idx_products_slug on products (slug);
create index idx_products_publish_status on products (publish_status);
create index idx_products_stock_state on products (stock_state);
create index idx_categories_slug on categories (slug);
create index idx_brands_slug on brands (slug);
create index idx_articles_slug on articles (slug);
create index idx_pages_slug on pages (slug);
