-- V225: Đưa toàn bộ copy trang Tra cứu bảo hành (/bao-hanh) — trước đây hardcode trong i18n
-- (namespace Warranty của bigbike-web) — vào site_settings nhóm public_warranty để admin sửa được
-- qua màn Cài đặt. Công cụ tra cứu serial giữ nguyên chức năng; chỉ phần chữ là động.
-- Seed = đúng nội dung đang hiển thị (VI + EN). Hai khối nội dung mới (intro_html, policy_html) và
-- hình minh hoạ (intro_image) seed rỗng → web ẩn cho tới khi admin soạn.
-- valueType/public do SettingDefinitionRegistry cung cấp; bảng chỉ giữ value/value_en/group/is_public.
-- Web đọc settings-first, fallback copy i18n khi key trống nên trang không bao giờ trắng.

insert into site_settings
    (id, setting_key, setting_value, setting_value_en, setting_group, is_public, description, created_at, updated_at)
values
    (gen_random_uuid(), 'warranty_page_meta_title',
        'Tra cứu bảo hành',
        'Warranty lookup',
        'public_warranty', true, 'Trang Bảo hành — tiêu đề SEO.', now(), now()),
    (gen_random_uuid(), 'warranty_page_meta_description',
        'Tra cứu thông tin bảo hành sản phẩm BigBike bằng số serial trên tem sản phẩm.',
        'Look up BigBike product warranty information using the serial number on the product label.',
        'public_warranty', true, 'Trang Bảo hành — mô tả SEO.', now(), now()),
    (gen_random_uuid(), 'warranty_page_heading',
        'Tra cứu bảo hành',
        'Warranty lookup',
        'public_warranty', true, 'Trang Bảo hành — tiêu đề banner.', now(), now()),
    (gen_random_uuid(), 'warranty_page_kicker',
        'Hậu mãi · BigBike',
        'After-sales · BigBike',
        'public_warranty', true, 'Trang Bảo hành — kicker.', now(), now()),
    (gen_random_uuid(), 'warranty_page_subheading',
        'Nhập số serial trên tem sản phẩm để kiểm tra hạn bảo hành.',
        'Enter the serial number on the product label to check warranty status.',
        'public_warranty', true, 'Trang Bảo hành — dòng mô tả.', now(), now()),
    (gen_random_uuid(), 'warranty_page_intro_html',
        '', null,
        'public_warranty', true, 'Trang Bảo hành — khối giới thiệu trên ô tra cứu (rich-text, rỗng = ẩn).', now(), now()),
    (gen_random_uuid(), 'warranty_page_intro_image',
        '', null,
        'public_warranty', true, 'Trang Bảo hành — hình minh hoạ khối giới thiệu (rỗng = ẩn).', now(), now()),
    (gen_random_uuid(), 'warranty_page_serial_label',
        'Số serial',
        'Serial number',
        'public_warranty', true, 'Trang Bảo hành — nhãn ô nhập serial.', now(), now()),
    (gen_random_uuid(), 'warranty_page_serial_placeholder',
        'VD: AGV-2024-001234',
        'E.g. AGV-2024-001234',
        'public_warranty', true, 'Trang Bảo hành — placeholder ô nhập serial.', now(), now()),
    (gen_random_uuid(), 'warranty_page_serial_hint',
        'Số serial in trên tem dán trong hộp sản phẩm hoặc trên thân sản phẩm.',
        'The serial number is printed on the label inside the box or on the product itself.',
        'public_warranty', true, 'Trang Bảo hành — hướng dẫn dưới ô nhập serial.', now(), now()),
    (gen_random_uuid(), 'warranty_page_submit_button',
        'Tra cứu',
        'Look up',
        'public_warranty', true, 'Trang Bảo hành — chữ nút tra cứu.', now(), now()),
    (gen_random_uuid(), 'warranty_page_submitting',
        'Đang tra...',
        'Looking up…',
        'public_warranty', true, 'Trang Bảo hành — chữ nút khi đang tra.', now(), now()),
    (gen_random_uuid(), 'warranty_page_not_found',
        'Không tìm thấy thông tin bảo hành.',
        'No warranty information found.',
        'public_warranty', true, 'Trang Bảo hành — thông báo không tìm thấy.', now(), now()),
    (gen_random_uuid(), 'warranty_page_result_heading',
        'Thông tin bảo hành',
        'Warranty information',
        'public_warranty', true, 'Trang Bảo hành — tiêu đề khối kết quả.', now(), now()),
    (gen_random_uuid(), 'warranty_page_field_product',
        'Sản phẩm',
        'Product',
        'public_warranty', true, 'Trang Bảo hành — nhãn dòng Sản phẩm.', now(), now()),
    (gen_random_uuid(), 'warranty_page_field_serial',
        'Số serial',
        'Serial number',
        'public_warranty', true, 'Trang Bảo hành — nhãn dòng Số serial.', now(), now()),
    (gen_random_uuid(), 'warranty_page_field_start',
        'Ngày bắt đầu',
        'Start date',
        'public_warranty', true, 'Trang Bảo hành — nhãn dòng Ngày bắt đầu.', now(), now()),
    (gen_random_uuid(), 'warranty_page_field_end',
        'Ngày kết thúc',
        'End date',
        'public_warranty', true, 'Trang Bảo hành — nhãn dòng Ngày kết thúc.', now(), now()),
    (gen_random_uuid(), 'warranty_page_status_active',
        'Còn hiệu lực ({daysLeft} ngày)',
        'Active ({daysLeft} days left)',
        'public_warranty', true, 'Trang Bảo hành — trạng thái Còn hiệu lực ({daysLeft}).', now(), now()),
    (gen_random_uuid(), 'warranty_page_status_almost_expired',
        'Sắp hết hạn ({daysLeft} ngày)',
        'Expiring soon ({daysLeft} days left)',
        'public_warranty', true, 'Trang Bảo hành — trạng thái Sắp hết hạn ({daysLeft}).', now(), now()),
    (gen_random_uuid(), 'warranty_page_status_expired',
        'Hết hạn',
        'Expired',
        'public_warranty', true, 'Trang Bảo hành — trạng thái Hết hạn.', now(), now()),
    (gen_random_uuid(), 'warranty_page_status_voided',
        'Đã huỷ',
        'Voided',
        'public_warranty', true, 'Trang Bảo hành — trạng thái Đã huỷ.', now(), now()),
    (gen_random_uuid(), 'warranty_page_footer_active',
        'Vui lòng giữ số serial để xuất trình khi yêu cầu bảo hành tại cửa hàng hoặc qua hotline.',
        'Please keep the serial number to present when requesting warranty service in-store or via hotline.',
        'public_warranty', true, 'Trang Bảo hành — ghi chú khi còn hiệu lực.', now(), now()),
    (gen_random_uuid(), 'warranty_page_footer_voided',
        'Phiếu bảo hành này đã bị huỷ. Liên hệ cửa hàng để được hỗ trợ.',
        'This warranty card has been voided. Please contact the store for assistance.',
        'public_warranty', true, 'Trang Bảo hành — ghi chú khi đã huỷ.', now(), now()),
    (gen_random_uuid(), 'warranty_page_policy_html',
        '', null,
        'public_warranty', true, 'Trang Bảo hành — khối chính sách / FAQ dưới kết quả (rich-text, rỗng = ẩn).', now(), now())
on conflict (setting_key) do nothing;
