-- V232: Per-product commitment rows (khối "cam kết" dưới nút mua hàng trên PDP).
-- Thay cho cấu hình CHUNG cũ ở nhóm public_product (product_commitment_*, V228):
-- giờ mỗi sản phẩm tự quản danh sách dòng cam kết, admin thêm/bớt linh hoạt, mỗi
-- dòng tự chọn icon. Mirror bảng con product_faqs (+ cột _en song ngữ inline).

create table product_commitments (
    id bigint generated by default as identity primary key,
    product_id varchar(64) not null,
    sort_order integer not null,
    icon varchar(40) not null,
    title varchar(200) not null,
    subtitle varchar(300),
    title_en varchar(200),
    subtitle_en varchar(300),
    constraint fk_product_commitments_product_id
        foreign key (product_id) references products (id) on delete cascade
);

create index if not exists idx_product_commitments_product_id on product_commitments (product_id);

-- Chép sẵn 3 dòng mặc định (giao hàng / đổi trả / bảo hành) cho MỌI sản phẩm hiện có,
-- lấy đúng nội dung đang hiển thị từ cấu hình chung cũ (giữ cả bản sửa của admin); icon
-- theo thứ tự dòng cũ (truck → refresh-cw → shield-check). Dòng nào admin đã bỏ trống
-- tiêu đề thì không chép (web vốn cũng ẩn dòng đó). Sản phẩm mới về sau admin tự nhập.
with cfg as (
    select
        max(case when setting_key = 'product_commitment_1_title' then setting_value end) as t1,
        max(case when setting_key = 'product_commitment_1_subtitle' then setting_value end) as s1,
        max(case when setting_key = 'product_commitment_1_title' then setting_value_en end) as t1e,
        max(case when setting_key = 'product_commitment_1_subtitle' then setting_value_en end) as s1e,
        max(case when setting_key = 'product_commitment_2_title' then setting_value end) as t2,
        max(case when setting_key = 'product_commitment_2_subtitle' then setting_value end) as s2,
        max(case when setting_key = 'product_commitment_2_title' then setting_value_en end) as t2e,
        max(case when setting_key = 'product_commitment_2_subtitle' then setting_value_en end) as s2e,
        max(case when setting_key = 'product_commitment_3_title' then setting_value end) as t3,
        max(case when setting_key = 'product_commitment_3_subtitle' then setting_value end) as s3,
        max(case when setting_key = 'product_commitment_3_title' then setting_value_en end) as t3e,
        max(case when setting_key = 'product_commitment_3_subtitle' then setting_value_en end) as s3e
    from site_settings
    where setting_key in (
        'product_commitment_1_title', 'product_commitment_1_subtitle',
        'product_commitment_2_title', 'product_commitment_2_subtitle',
        'product_commitment_3_title', 'product_commitment_3_subtitle'
    )
),
default_rows as (
    select 0 as sort_order, 'truck'        as icon, t1 as title, s1 as subtitle, t1e as title_en, s1e as subtitle_en from cfg
    union all
    select 1, 'refresh-cw',   t2, s2, t2e, s2e from cfg
    union all
    select 2, 'shield-check',  t3, s3, t3e, s3e from cfg
)
insert into product_commitments (product_id, sort_order, icon, title, subtitle, title_en, subtitle_en)
select p.id, r.sort_order, r.icon, r.title, r.subtitle, r.title_en, r.subtitle_en
from products p
cross join default_rows r
where r.title is not null and btrim(r.title) <> '';

-- Gỡ 6 khóa cấu hình chung cũ (không còn dùng). Giữ product_trust_genuine/_freeship.
delete from site_settings
where setting_key in (
    'product_commitment_1_title', 'product_commitment_1_subtitle',
    'product_commitment_2_title', 'product_commitment_2_subtitle',
    'product_commitment_3_title', 'product_commitment_3_subtitle'
);
