-- V233: Per-product trust badges (dải tín hiệu tin cậy hiển thị NGAY TRÊN tên sản phẩm trên PDP,
-- vd "Chính hãng" / "BH 2 năm" / "Freeship"). Thay cho 2 nhãn CHUNG cũ ở nhóm public_product
-- (product_trust_genuine / product_trust_freeship): giờ MỖI sản phẩm tự quản danh sách badge ngắn,
-- admin thêm/bớt/sắp xếp linh hoạt, song ngữ. Để trống → web ẩn dải. Mirror bảng con product_commitments.
-- KHÔNG seed mặc định: theo yêu cầu vận hành, sản phẩm bắt đầu RỖNG, admin tự nhập riêng từng sản phẩm.

create table product_trust_badges (
    id bigint generated by default as identity primary key,
    product_id varchar(64) not null,
    sort_order integer not null,
    content varchar(200) not null,
    content_en varchar(200),
    constraint fk_product_trust_badges_product_id
        foreign key (product_id) references products (id) on delete cascade
);

create index if not exists idx_product_trust_badges_product_id on product_trust_badges (product_id);

-- Gỡ 2 khóa nhãn chung cũ (không còn dùng — trust row giờ quản theo từng sản phẩm).
delete from site_settings
where setting_key in ('product_trust_genuine', 'product_trust_freeship');
