-- V235: "Specs Dashboard" — ô số liệu nổi bật ngay dưới khu vực mua hàng trên PDP.
-- Tách hẳn khỏi bảng thông số kỹ thuật: đây là "đòn chốt" bán hàng (số liệu lớn +
-- nhãn), admin tự nhập theo TỪNG sản phẩm, tối đa 4 ô. Thay cho cờ
-- product_specifications.featured (V230) — cờ đó nay bị gỡ bỏ. Mirror bảng con
-- product_commitments (+ cột _en song ngữ inline).

create table product_spec_stats (
    id bigint generated by default as identity primary key,
    product_id varchar(64) not null,
    sort_order integer not null,
    stat_value varchar(60) not null,
    label varchar(80) not null,
    stat_value_en varchar(60),
    label_en varchar(80),
    constraint fk_product_spec_stats_product_id
        foreign key (product_id) references products (id) on delete cascade
);

create index if not exists idx_product_spec_stats_product_id on product_spec_stats (product_id);

-- Chuyển sẵn các thông số đang được tích "nổi bật" (featured=true) sang ô số liệu mới,
-- để trang không bị trống lúc ra mắt. Giữ tối đa 4 ô/sản phẩm theo đúng thứ tự cũ
-- (web vốn cũng chỉ hiện 4). value = giá trị thông số, label = tên thông số; cắt
-- theo độ dài cột mới. Sau khi nhập, admin chỉnh lại cho "đáng tiền" hơn.
insert into product_spec_stats (product_id, sort_order, stat_value, label, stat_value_en, label_en)
select product_id, rn - 1 as sort_order,
       left(spec_value, 60) as stat_value,
       left(name, 80) as label,
       left(spec_value_en, 60) as stat_value_en,
       left(name_en, 80) as label_en
from (
    select s.product_id, s.spec_value, s.name, s.spec_value_en, s.name_en,
           row_number() over (partition by s.product_id order by s.sort_order, s.id) as rn
    from product_specifications s
    where s.featured = true
      and btrim(coalesce(s.spec_value, '')) <> ''
      and btrim(coalesce(s.name, '')) <> ''
) ranked
where rn <= 4;

-- Gỡ cờ "đưa lên ô nổi bật" khỏi thông số kỹ thuật (không còn dùng).
alter table product_specifications drop column featured;
