-- V252: Per-product "Mua tại BigBike.vn" lines (khối mua hàng trên PDP). Thay cho 4 trường
-- riêng lẻ (warranty_months / warranty_scope / pdp_shipping_line / pdp_return_line, V175/V247):
-- giờ mỗi sản phẩm tự quản danh sách dòng (Bảo hành / Giao hàng / Đổi trả …), admin thêm/bớt
-- linh hoạt, mỗi dòng tự chọn icon + nhãn + giá trị. Mirror bảng con product_commitments (V232).
--
-- 4 cột cũ trên products GIỮ NGUYÊN (dormant) — chỉ gỡ ở tầng ứng dụng, dữ liệu đã backfill
-- xuống bảng này nên không drop để tránh mất dữ liệu / rollback an toàn.

create table product_purchase_lines (
    id bigint generated by default as identity primary key,
    product_id varchar(64) not null,
    sort_order integer not null,
    icon varchar(40) not null,
    label varchar(200) not null,
    value varchar(300),
    label_en varchar(200),
    value_en varchar(300),
    constraint fk_product_purchase_lines_product_id
        foreign key (product_id) references products (id) on delete cascade
);

create index if not exists idx_product_purchase_lines_product_id on product_purchase_lines (product_id);

-- Backfill 3 ô cũ (Bảo hành / Giao hàng / Đổi trả) cho MỌI sản phẩm hiện có, lấy đúng nội dung
-- đang lưu trên products. Chỉ chèn dòng có giá trị non-blank. Sản phẩm mới về sau admin tự nhập.

-- Bảo hành (sort 0): ưu tiên warranty_months → "N tháng"; nếu null thì dùng warranty_scope (text).
insert into product_purchase_lines (product_id, sort_order, icon, label, value, label_en, value_en)
select p.id, 0, 'shield-check', 'Bảo hành',
       p.warranty_months || ' tháng', 'Warranty', p.warranty_months || ' months'
from products p
where p.warranty_months is not null;

insert into product_purchase_lines (product_id, sort_order, icon, label, value, label_en, value_en)
select p.id, 0, 'shield-check', 'Bảo hành', p.warranty_scope, 'Warranty', null
from products p
where p.warranty_months is null
  and p.warranty_scope is not null and btrim(p.warranty_scope) <> '';

-- Giao hàng (sort 1): pdp_shipping_line.
insert into product_purchase_lines (product_id, sort_order, icon, label, value, label_en, value_en)
select p.id, 1, 'truck', 'Giao hàng', p.pdp_shipping_line, 'Shipping', null
from products p
where p.pdp_shipping_line is not null and btrim(p.pdp_shipping_line) <> '';

-- Đổi trả (sort 2): pdp_return_line.
insert into product_purchase_lines (product_id, sort_order, icon, label, value, label_en, value_en)
select p.id, 2, 'refresh-cw', 'Đổi trả', p.pdp_return_line, 'Return', null
from products p
where p.pdp_return_line is not null and btrim(p.pdp_return_line) <> '';
