-- V269: Seed nhóm settings PUBLIC_ABOUT (trang Giới thiệu /gioi-thieu).
-- Nhóm này được khai báo trong SettingDefinitionRegistry nhưng CHƯA bao giờ có dòng dữ liệu
-- (mọi nhóm public khác đã được seed) → tab "Trang Giới thiệu" không hiện trong admin Cài đặt,
-- admin không sửa được chữ/ảnh ô dịch vụ. Seed để mở khóa chỗ sửa đó.
--
-- Chữ điền sẵn = bản mặc định đang hiển thị (i18n About, VI) → web KHÔNG đổi giao diện
-- (web vốn fallback về đúng các chuỗi này khi settings trống). EN để trống: API tự fallback VI.
-- 5 ảnh ô dịch vụ để trống: web tiếp tục dùng icon mặc định của theme (a-1..a-5) cho tới khi
-- admin tự upload (IMAGE_URL chỉ nhận URL tuyệt đối → upload lưu vào MinIO). Idempotent.
-- valueType do SettingDefinitionRegistry quyết định trong code — không lưu ở DB.

insert into site_settings (id, setting_key, setting_value, setting_group, is_public, description, created_at, updated_at)
values
    (gen_random_uuid(), 'about_page_kicker', 'Bigbike', 'public_about', true, 'Đầu trang — tiêu đề nhỏ (kicker).', now(), now()),
    (gen_random_uuid(), 'about_page_tagline', 'Cửa hàng chuyên phân phối phụ kiện bảo hộ moto chính hãng uy tín tại TP HCM', 'public_about', true, 'Đầu trang — câu tagline.', now(), now()),
    (gen_random_uuid(), 'about_page_intro_html', '<p>Thời gian gần đây, du lịch phượt đang dần trở thành trào lưu trải nghiệm mang tính lan tỏa nhanh chóng, thu hút ngày càng đông mọi người tham gia, đặc biệt là những người đam mê xe phân khối lớn. Và hầu hết các biker luôn mong muốn tìm kiếm và trang bị các thiết bị bảo hộ moto chất lượng nhằm đảm bảo an toàn cho chuyến hành trình của mình.</p><p>Được thành lập từ năm 2013, Bigbike hiện là một trong những nhà cung cấp đồ bảo hộ moto uy tín tại TP HCM. Chúng tôi tự hào là người bạn đồng hành đáng tin cậy của cộng đồng biker Việt Nam trong suốt thời gian qua.</p><p>Chúng tôi cung cấp các dòng sản phẩm như mũ bảo hiểm, quần - áo bảo hộ, găng tay và giày bảo hộ moto chính hãng từ các thương hiệu nổi tiếng trên thế giới như Alpinestars, Helite, Furygan, LS2, Scoyco, Sena và SCS. Các sản phẩm của Bigbike sở hữu nhiều thiết kế đa dạng với những kiểu dáng và mẫu mã khác nhau để đáp ứng mọi nhu cầu của khách hàng.</p><p>Đến với Bigbike, khách hàng có thể hoàn toàn yên tâm về chất lượng của các sản phẩm. Những dòng sản phẩm bảo hộ đều được đảm bảo đạt đủ các tiêu chuẩn an toàn nên các biker có thể hoàn toàn yên tâm khi sử dụng.</p>', 'public_about', true, 'Đoạn giới thiệu mở đầu (rich-text).', now(), now()),
    (gen_random_uuid(), 'about_page_quality_heading', 'Chất lượng dịch vụ tạo nên sự khác biệt', 'public_about', true, 'Khối chất lượng — tiêu đề.', now(), now()),
    (gen_random_uuid(), 'about_page_quality_body', 'Trong suốt quá trình hoạt động của mình, Bigbike đã được hân hạnh được trở thành nhà tài trợ đồng hành cho các sự kiện sinh nhật, kỉ niệm và từ thiện cùng câu lạc bộ xe exciter và câu lạc bộ moto Việt Nam. Bigbike luôn lắng nghe và ghi nhận những ý kiến đóng góp của khách hàng. Để từ đó, chúng tôi không ngừng nỗ lực cải thiện và nâng cao chất lượng dịch vụ. Sự hài lòng của khách hàng chính là sự thành công của Bigbike.', 'public_about', true, 'Khối chất lượng — mô tả.', now(), now()),
    (gen_random_uuid(), 'about_page_service1_title', 'Các chương trình khuyến mãi hấp dẫn', 'public_about', true, 'Ô dịch vụ 1 — tiêu đề.', now(), now()),
    (gen_random_uuid(), 'about_page_service1_body', 'Ngoài ra, những thông tin, tin tức mới nhất về các sản phẩm moto cũng như các sự kiện nổi bật cũng luôn được chúng tôi cập nhật thường xuyên trên website chính thức của Bigbike. Ngoài ra, các biker có thể tham khảo thêm một số bài viết so sánh và đánh giá về các trang thiết bị bảo hộ phượt tại đây.', 'public_about', true, 'Ô dịch vụ 1 — mô tả.', now(), now()),
    (gen_random_uuid(), 'about_page_service1_image', '', 'public_about', true, 'Ô dịch vụ 1 — hình (~120×120px PNG nền trong). Để trống = dùng icon mặc định của giao diện.', now(), now()),
    (gen_random_uuid(), 'about_page_service1_highlight', 'true', 'public_about', true, 'Ô dịch vụ 1 — nền cam nổi bật (true/false).', now(), now()),
    (gen_random_uuid(), 'about_page_service2_title', 'Cập nhật xu hướng liên tục', 'public_about', true, 'Ô dịch vụ 2 — tiêu đề.', now(), now()),
    (gen_random_uuid(), 'about_page_service2_body', 'Những xu hướng và mẫu mã sản phẩm thịnh hành nhất trên thị trường hiện nay luôn được Bigbike cập nhật liên tục nhằm đáp ứng kịp thời thị hiếu và nhu cầu từ cơ bản đến nâng cao của khách hàng. Và chúng tôi thường xuyên có những chương trình ưu đãi và hậu mãi hấp dẫn để đem đến cho các biker nhiều cơ hội trải nghiệm sản phẩm cũng như tri ân khách hàng thân thiết.', 'public_about', true, 'Ô dịch vụ 2 — mô tả.', now(), now()),
    (gen_random_uuid(), 'about_page_service2_image', '', 'public_about', true, 'Ô dịch vụ 2 — hình (~120×120px PNG nền trong). Để trống = dùng icon mặc định của giao diện.', now(), now()),
    (gen_random_uuid(), 'about_page_service2_highlight', 'false', 'public_about', true, 'Ô dịch vụ 2 — nền cam nổi bật (true/false).', now(), now()),
    (gen_random_uuid(), 'about_page_service3_title', 'Chất lượng dịch vụ tạo nên sự khác biệt', 'public_about', true, 'Ô dịch vụ 3 — tiêu đề.', now(), now()),
    (gen_random_uuid(), 'about_page_service3_body', 'Khi đến với Bigbike, khách hàng sẽ được tư vấn kỹ lượng về mọi thông tin chi tiết sản phẩm cũng như được giải đáp các thắc mắc một cách tận tình và chu đáo. Đội ngũ nhân viên Bigbike được đào tạo chuyên nghiệp và có sự am hiểu thông tin của sản phẩm sẽ luôn sẵn sàng tư vấn và hỗ trợ khách hàng khi cần thiết. Bạn có thể trực tiếp kiểm tra chất lượng sản phẩm và lựa chọn cho mình các vật dụng bảo hộ phù hợp nhất.', 'public_about', true, 'Ô dịch vụ 3 — mô tả.', now(), now()),
    (gen_random_uuid(), 'about_page_service3_image', '', 'public_about', true, 'Ô dịch vụ 3 — hình (~120×120px PNG nền trong). Để trống = dùng icon mặc định của giao diện.', now(), now()),
    (gen_random_uuid(), 'about_page_service3_highlight', 'false', 'public_about', true, 'Ô dịch vụ 3 — nền cam nổi bật (true/false).', now(), now()),
    (gen_random_uuid(), 'about_page_service4_title', 'Dịch vụ hậu cần tối ưu', 'public_about', true, 'Ô dịch vụ 4 — tiêu đề.', now(), now()),
    (gen_random_uuid(), 'about_page_service4_body', 'Các dịch vụ hậu cần cũng luôn được thực hiện nhanh chóng. Các hoạt động giao nhận hàng hóa, các chính sách bảo hành và đổi trả sản phẩm luôn được áp dụng tiện lợi nhất cho khách hàng. Các quy trình luôn được chú trọng và được thực hiện cẩn thận, từ khâu đóng gói hàng hóa cho đến khâu vận chuyển. Nhằm đảm bảo hàng hóa được giao đến tay khách hàng với trạng thái tốt nhất.', 'public_about', true, 'Ô dịch vụ 4 — mô tả.', now(), now()),
    (gen_random_uuid(), 'about_page_service4_image', '', 'public_about', true, 'Ô dịch vụ 4 — hình (~120×120px PNG nền trong). Để trống = dùng icon mặc định của giao diện.', now(), now()),
    (gen_random_uuid(), 'about_page_service4_highlight', 'false', 'public_about', true, 'Ô dịch vụ 4 — nền cam nổi bật (true/false).', now(), now()),
    (gen_random_uuid(), 'about_page_service5_title', 'Các thông tin nổi bật luôn được cập nhật nhanh chóng', 'public_about', true, 'Ô dịch vụ 5 — tiêu đề.', now(), now()),
    (gen_random_uuid(), 'about_page_service5_body', 'Chúng tôi cung cấp đầy đủ những gì bạn cần cho một cuộc hành trình. Bigbike tự hào luôn nhận được sự tin tưởng cũng như những đánh giá tích cực từ khách hàng và là đơn vị uy tín và xứng đáng để bạn trao gửi niềm tin.', 'public_about', true, 'Ô dịch vụ 5 — mô tả.', now(), now()),
    (gen_random_uuid(), 'about_page_service5_image', '', 'public_about', true, 'Ô dịch vụ 5 — hình (~120×120px PNG nền trong). Để trống = dùng icon mặc định của giao diện.', now(), now()),
    (gen_random_uuid(), 'about_page_service5_highlight', 'true', 'public_about', true, 'Ô dịch vụ 5 — nền cam nổi bật (true/false).', now(), now()),
    (gen_random_uuid(), 'about_page_connect_heading', 'KẾT NỐI ĐỂ CHÚNG TÔI CÓ THỂ GẦN BẠN HƠN', 'public_about', true, 'Khối kết nối — tiêu đề.', now(), now()),
    (gen_random_uuid(), 'about_page_connect_intro1', 'Bigbike hiện đã nhận được hơn 80 lượt review 5 sao trên Google map và nhận được nhiều lời khen ngợi khác. Đây chính là những động lực to lớn để chúng tôi tiếp tục cố gắng trở thành người bạn đồng hành tốt nhất của cộng đồng biker Việt Nam.', 'public_about', true, 'Khối kết nối — dòng 1.', now(), now()),
    (gen_random_uuid(), 'about_page_connect_intro2', 'Hãy liên hệ với chúng tôi để được tư vấn thêm về các thông tin chi tiết sản phẩm và để nhận được giá ưu đãi tốt nhất.', 'public_about', true, 'Khối kết nối — dòng 2.', now(), now())
on conflict (setting_key) do nothing;
