package com.bigbike.bigbike_backend.migration;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.StringReader;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.UUID;
import org.h2.tools.RunScript;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;

/** Fixture-level verification for the narrow, idempotent V354 legacy cleanup. */
class LegacyProductImportCleanupMigrationTest {

    @Test
    void v354CleansOnlyApprovedLegacyArtifactsAndIsIdempotent() throws Exception {
        String databaseName = "v354_" + UUID.randomUUID().toString().replace("-", "");
        try (Connection connection = DriverManager.getConnection(
                "jdbc:h2:mem:" + databaseName + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE")) {
            createRelevantSchema(connection);
            seedLegacyArtifacts(connection);

            executeMigration(connection);
            assertCleanedState(connection);

            executeMigration(connection);
            assertCleanedState(connection);
        }
    }

    private void createRelevantSchema(Connection connection) throws SQLException {
        execute(connection, """
                CREATE TABLE products (
                    id VARCHAR(64) PRIMARY KEY,
                    available BOOLEAN NOT NULL,
                    stock_state VARCHAR(32) NOT NULL
                )
                """);
        execute(connection, """
                CREATE TABLE product_variants (
                    id VARCHAR(64) PRIMARY KEY,
                    product_id VARCHAR(64) NOT NULL REFERENCES products(id),
                    image_id VARCHAR(64),
                    image_url TEXT,
                    image_alt VARCHAR(255),
                    image_width INTEGER,
                    image_height INTEGER,
                    image_mime_type VARCHAR(100)
                )
                """);
        execute(connection, """
                CREATE TABLE product_variant_gallery_images (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    variant_id VARCHAR(64) NOT NULL REFERENCES product_variants(id),
                    sort_order INTEGER NOT NULL,
                    media_type VARCHAR(8),
                    image_id VARCHAR(64),
                    image_url TEXT,
                    image_alt VARCHAR(255),
                    image_width INTEGER,
                    image_height INTEGER,
                    image_mime_type VARCHAR(100)
                )
                """);
        // Nullable fields exercise V354's defensive NULL branches even though the
        // production table currently declares both columns NOT NULL.
        execute(connection, """
                CREATE TABLE product_variant_options (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    variant_id VARCHAR(64) NOT NULL REFERENCES product_variants(id),
                    option_name VARCHAR(255),
                    option_value VARCHAR(255)
                )
                """);
    }

    private void seedLegacyArtifacts(Connection connection) throws SQLException {
        execute(connection, """
                INSERT INTO products (id, available, stock_state) VALUES
                    ('p-no-variant-target', true, 'OUT_OF_STOCK'),
                    ('p-no-variant-in-stock', true, 'IN_STOCK'),
                    ('p-no-variant-disabled', false, 'OUT_OF_STOCK'),
                    ('p-with-variants', true, 'OUT_OF_STOCK')
                """);
        execute(connection, """
                INSERT INTO product_variants (
                    id, product_id, image_id, image_url, image_alt,
                    image_width, image_height, image_mime_type
                ) VALUES
                    ('v-missing-cover', 'p-with-variants', NULL, NULL, NULL, NULL, NULL, NULL),
                    ('v-existing-cover', 'p-with-variants', 'manual', 'manual.jpg', 'Manual',
                        640, 480, 'image/jpeg'),
                    ('v-no-valid-image', 'p-with-variants', NULL, NULL, NULL, NULL, NULL, NULL)
                """);
        execute(connection, """
                INSERT INTO product_variant_gallery_images (
                    id, variant_id, sort_order, media_type, image_id, image_url, image_alt,
                    image_width, image_height, image_mime_type
                ) VALUES
                    (10, 'v-missing-cover', 0, 'video', 'poster', 'poster.jpg', 'Poster',
                        320, 180, 'image/jpeg'),
                    (11, 'v-missing-cover', 1, 'image', 'blank', '   ', 'Blank',
                        1, 1, 'image/jpeg'),
                    (12, 'v-missing-cover', 2, 'image', 'first', 'first.jpg', 'First',
                        1200, 800, 'image/webp'),
                    (13, 'v-missing-cover', 2, 'image', 'second', 'second.jpg', 'Second',
                        1000, 700, 'image/jpeg'),
                    (20, 'v-existing-cover', 0, 'image', 'gallery', 'gallery.jpg', 'Gallery',
                        900, 600, 'image/jpeg'),
                    (30, 'v-no-valid-image', 0, 'video', NULL, 'clip.mp4', NULL,
                        NULL, NULL, NULL)
                """);
        execute(connection, """
                INSERT INTO product_variant_options (id, variant_id, option_name, option_value) VALUES
                    (1, 'v-missing-cover', NULL, 'red'),
                    (2, 'v-missing-cover', '   ', 'red'),
                    (3, 'v-missing-cover', 'size', NULL),
                    (4, 'v-missing-cover', 'size', '   '),
                    (5, 'v-missing-cover', 'size', 'L')
                """);
    }

    private void executeMigration(Connection connection) throws Exception {
        String migrationSql = new ClassPathResource(
                "db/migration/V354__clean_legacy_product_import_artifacts.sql"
        ).getContentAsString(StandardCharsets.UTF_8);
        RunScript.execute(connection, new StringReader(migrationSql));
    }

    private void assertCleanedState(Connection connection) throws SQLException {
        assertThat(booleanValue(connection,
                "SELECT available FROM products WHERE id = 'p-no-variant-target'")).isFalse();
        assertThat(booleanValue(connection,
                "SELECT available FROM products WHERE id = 'p-no-variant-in-stock'")).isTrue();
        assertThat(booleanValue(connection,
                "SELECT available FROM products WHERE id = 'p-no-variant-disabled'")).isFalse();
        assertThat(booleanValue(connection,
                "SELECT available FROM products WHERE id = 'p-with-variants'")).isTrue();

        assertThat(stringValue(connection,
                "SELECT image_id FROM product_variants WHERE id = 'v-missing-cover'"))
                .isEqualTo("first");
        assertThat(stringValue(connection,
                "SELECT image_url FROM product_variants WHERE id = 'v-missing-cover'"))
                .isEqualTo("first.jpg");
        assertThat(stringValue(connection,
                "SELECT image_alt FROM product_variants WHERE id = 'v-missing-cover'"))
                .isEqualTo("First");
        assertThat(integerValue(connection,
                "SELECT image_width FROM product_variants WHERE id = 'v-missing-cover'"))
                .isEqualTo(1200);
        assertThat(integerValue(connection,
                "SELECT image_height FROM product_variants WHERE id = 'v-missing-cover'"))
                .isEqualTo(800);
        assertThat(stringValue(connection,
                "SELECT image_mime_type FROM product_variants WHERE id = 'v-missing-cover'"))
                .isEqualTo("image/webp");

        assertThat(stringValue(connection,
                "SELECT image_url FROM product_variants WHERE id = 'v-existing-cover'"))
                .isEqualTo("manual.jpg");
        assertThat(stringValue(connection,
                "SELECT image_url FROM product_variants WHERE id = 'v-no-valid-image'"))
                .isNull();

        assertThat(integerValue(connection, "SELECT COUNT(*) FROM product_variants")).isEqualTo(3);
        assertThat(integerValue(connection, "SELECT COUNT(*) FROM product_variant_options")).isEqualTo(1);
        assertThat(stringValue(connection, "SELECT option_name FROM product_variant_options"))
                .isEqualTo("size");
        assertThat(stringValue(connection, "SELECT option_value FROM product_variant_options"))
                .isEqualTo("L");
    }

    private void execute(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement()) {
            statement.execute(sql);
        }
    }

    private Boolean booleanValue(Connection connection, String sql) throws SQLException {
        return (Boolean) scalar(connection, sql);
    }

    private Integer integerValue(Connection connection, String sql) throws SQLException {
        return ((Number) scalar(connection, sql)).intValue();
    }

    private String stringValue(Connection connection, String sql) throws SQLException {
        Object value = scalar(connection, sql);
        return value == null ? null : value.toString();
    }

    private Object scalar(Connection connection, String sql) throws SQLException {
        try (Statement statement = connection.createStatement();
                ResultSet result = statement.executeQuery(sql)) {
            assertThat(result.next()).isTrue();
            return result.getObject(1);
        }
    }
}
