import { stripHtmlToText } from "@/lib/utils/text";

export type CategoryFaq = {
  question: string;
  answer: string;
};

/**
 * Reads the FAQ rows generated by the category-intro form. The public HTML
 * intentionally carries headings only; FAQPage JSON-LD is emitted separately
 * by the category route so the same questions are not declared twice.
 */
export function extractCategoryFaqs(html: string | null | undefined): CategoryFaq[] {
  if (!html?.trim()) return [];

  const questions = extractClassText(html, "bb-ci-qt", ["h3", "span"]);
  const answers = extractClassText(html, "bb-ci-at", ["p"]);
  const count = Math.min(questions.length, answers.length);

  return Array.from({ length: count }, (_, index) => ({
    question: questions[index],
    answer: answers[index],
  })).filter((faq) => Boolean(faq.question && faq.answer));
}

function extractClassText(html: string, className: string, tags: string[]): string[] {
  const tagPattern = tags.join("|");
  const classPattern = new RegExp(
    `<(?:${tagPattern})\\b[^>]*\\bclass=["'][^"']*\\b${className}\\b[^"']*["'][^>]*>([\\s\\S]*?)</(?:${tagPattern})>`,
    "gi",
  );
  return Array.from(html.matchAll(classPattern))
    .map((match) => stripHtmlToText(match[1] ?? ""))
    .filter(Boolean);
}
