package com.bigbike.bigbike_backend.api.admin.dto.order;

import com.bigbike.bigbike_backend.api.order.dto.OrderAddressResponse;
import com.bigbike.bigbike_backend.api.order.dto.OrderLineItemResponse;
import com.bigbike.bigbike_backend.api.order.dto.OrderPaymentResponse;
import com.bigbike.bigbike_backend.api.order.dto.OrderShippingItemResponse;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.List;
import java.util.UUID;

public record AdminOrderDetailResponse(
        UUID id,
        String orderNumber,
        String orderKey,
        String status,
        String paymentStatus,
        String fulfillmentStatus,
        String customerEmail,
        String customerPhone,
        String customerNote,
        String currency,
        String source,
        BigDecimal subtotalAmount,
        BigDecimal discountAmount,
        BigDecimal shippingAmount,
        BigDecimal feeAmount,
        BigDecimal taxAmount,
        BigDecimal totalAmount,
        BigDecimal paidAmount,
        BigDecimal refundAmount,
        String refundReason,
        Instant placedAt,
        Instant paidAt,
        Instant completedAt,
        Instant cancelledAt,
        Instant refundedAt,
        List<OrderLineItemResponse> lineItems,
        List<OrderAddressResponse> addresses,
        List<OrderShippingItemResponse> shippingItems,
        List<OrderPaymentResponse> payments,
        List<AdminOrderNoteResponse> notes,
        List<OrderAppliedCouponResponse> appliedCoupons
) {}
