export type VnDistrict = { code: string; name: string };
export type VnProvince = { code: string; name: string; districts: VnDistrict[] };

export const VN_PROVINCES: VnProvince[] = [
  { code: "01", name: "Hà Nội", districts: [
    { code: "001", name: "Quận Ba Đình" }, { code: "002", name: "Quận Hoàn Kiếm" },
    { code: "003", name: "Quận Tây Hồ" }, { code: "004", name: "Quận Long Biên" },
    { code: "005", name: "Quận Cầu Giấy" }, { code: "006", name: "Quận Đống Đa" },
    { code: "007", name: "Quận Hai Bà Trưng" }, { code: "008", name: "Quận Hoàng Mai" },
    { code: "009", name: "Quận Thanh Xuân" }, { code: "010", name: "Quận Nam Từ Liêm" },
    { code: "011", name: "Quận Bắc Từ Liêm" }, { code: "012", name: "Quận Hà Đông" },
    { code: "013", name: "Thị xã Sơn Tây" }, { code: "016", name: "Huyện Sóc Sơn" },
    { code: "017", name: "Huyện Đông Anh" }, { code: "018", name: "Huyện Gia Lâm" },
    { code: "019", name: "Huyện Thanh Trì" }, { code: "020", name: "Huyện Mê Linh" },
    { code: "021", name: "Huyện Ba Vì" }, { code: "022", name: "Huyện Phúc Thọ" },
    { code: "023", name: "Huyện Đan Phượng" }, { code: "024", name: "Huyện Hoài Đức" },
    { code: "025", name: "Huyện Quốc Oai" }, { code: "026", name: "Huyện Thạch Thất" },
    { code: "027", name: "Huyện Chương Mỹ" }, { code: "028", name: "Huyện Thanh Oai" },
    { code: "029", name: "Huyện Thường Tín" }, { code: "030", name: "Huyện Phú Xuyên" },
    { code: "031", name: "Huyện Ứng Hòa" }, { code: "032", name: "Huyện Mỹ Đức" },
  ]},
  { code: "02", name: "Hà Giang", districts: [
    { code: "024", name: "Thành phố Hà Giang" }, { code: "026", name: "Huyện Đồng Văn" },
    { code: "027", name: "Huyện Mèo Vạc" }, { code: "028", name: "Huyện Yên Minh" },
    { code: "029", name: "Huyện Quản Bạ" }, { code: "030", name: "Huyện Vị Xuyên" },
    { code: "031", name: "Huyện Bắc Mê" }, { code: "032", name: "Huyện Hoàng Su Phì" },
    { code: "033", name: "Huyện Xín Mần" }, { code: "034", name: "Huyện Bắc Quang" },
    { code: "035", name: "Huyện Quang Bình" },
  ]},
  { code: "04", name: "Cao Bằng", districts: [
    { code: "040", name: "Thành phố Cao Bằng" }, { code: "042", name: "Huyện Bảo Lâm" },
    { code: "043", name: "Huyện Bảo Lạc" }, { code: "044", name: "Huyện Hà Quảng" },
    { code: "045", name: "Huyện Trùng Khánh" }, { code: "046", name: "Huyện Hạ Lang" },
    { code: "047", name: "Huyện Quảng Uyên" }, { code: "048", name: "Huyện Phục Hoà" },
    { code: "049", name: "Huyện Hoà An" }, { code: "051", name: "Huyện Nguyên Bình" },
    { code: "052", name: "Huyện Thạch An" },
  ]},
  { code: "06", name: "Bắc Kạn", districts: [
    { code: "058", name: "Thành phố Bắc Kạn" }, { code: "060", name: "Huyện Pác Nặm" },
    { code: "061", name: "Huyện Ba Bể" }, { code: "062", name: "Huyện Ngân Sơn" },
    { code: "063", name: "Huyện Bạch Thông" }, { code: "064", name: "Huyện Chợ Đồn" },
    { code: "065", name: "Huyện Chợ Mới" }, { code: "066", name: "Huyện Na Rì" },
  ]},
  { code: "08", name: "Tuyên Quang", districts: [
    { code: "070", name: "Thành phố Tuyên Quang" }, { code: "071", name: "Huyện Lâm Bình" },
    { code: "072", name: "Huyện Na Hang" }, { code: "073", name: "Huyện Chiêm Hóa" },
    { code: "074", name: "Huyện Hàm Yên" }, { code: "075", name: "Huyện Yên Sơn" },
    { code: "076", name: "Huyện Sơn Dương" },
  ]},
  { code: "10", name: "Lào Cai", districts: [
    { code: "080", name: "Thành phố Lào Cai" }, { code: "082", name: "Huyện Bát Xát" },
    { code: "083", name: "Huyện Mường Khương" }, { code: "084", name: "Huyện Si Ma Cai" },
    { code: "085", name: "Huyện Bắc Hà" }, { code: "086", name: "Huyện Bảo Thắng" },
    { code: "087", name: "Huyện Bảo Yên" }, { code: "088", name: "Huyện Sa Pa" },
    { code: "089", name: "Huyện Văn Bàn" },
  ]},
  { code: "11", name: "Điện Biên", districts: [
    { code: "094", name: "Thành phố Điện Biên Phủ" }, { code: "095", name: "Thị xã Mường Lay" },
    { code: "096", name: "Huyện Mường Nhé" }, { code: "097", name: "Huyện Mường Chà" },
    { code: "098", name: "Huyện Tủa Chùa" }, { code: "099", name: "Huyện Tuần Giáo" },
    { code: "100", name: "Huyện Điện Biên" }, { code: "101", name: "Huyện Điện Biên Đông" },
    { code: "102", name: "Huyện Mường Ảng" }, { code: "103", name: "Huyện Nậm Pồ" },
  ]},
  { code: "12", name: "Lai Châu", districts: [
    { code: "105", name: "Thành phố Lai Châu" }, { code: "106", name: "Huyện Tam Đường" },
    { code: "107", name: "Huyện Mường Tè" }, { code: "108", name: "Huyện Sìn Hồ" },
    { code: "109", name: "Huyện Phong Thổ" }, { code: "110", name: "Huyện Than Uyên" },
    { code: "111", name: "Huyện Tân Uyên" }, { code: "112", name: "Huyện Nậm Nhùn" },
  ]},
  { code: "14", name: "Sơn La", districts: [
    { code: "116", name: "Thành phố Sơn La" }, { code: "118", name: "Huyện Quỳnh Nhai" },
    { code: "119", name: "Huyện Thuận Châu" }, { code: "120", name: "Huyện Mường La" },
    { code: "121", name: "Huyện Bắc Yên" }, { code: "122", name: "Huyện Phù Yên" },
    { code: "123", name: "Huyện Mộc Châu" }, { code: "124", name: "Huyện Yên Châu" },
    { code: "125", name: "Huyện Mai Sơn" }, { code: "126", name: "Huyện Sông Mã" },
    { code: "127", name: "Huyện Sốp Cộp" }, { code: "128", name: "Huyện Vân Hồ" },
  ]},
  { code: "15", name: "Yên Bái", districts: [
    { code: "132", name: "Thành phố Yên Bái" }, { code: "133", name: "Thị xã Nghĩa Lộ" },
    { code: "135", name: "Huyện Lục Yên" }, { code: "136", name: "Huyện Văn Yên" },
    { code: "137", name: "Huyện Mù Cang Chải" }, { code: "138", name: "Huyện Trấn Yên" },
    { code: "139", name: "Huyện Trạm Tấu" }, { code: "140", name: "Huyện Văn Chấn" },
    { code: "141", name: "Huyện Yên Bình" },
  ]},
  { code: "17", name: "Hoà Bình", districts: [
    { code: "148", name: "Thành phố Hòa Bình" }, { code: "150", name: "Huyện Đà Bắc" },
    { code: "151", name: "Huyện Lương Sơn" }, { code: "152", name: "Huyện Kim Bôi" },
    { code: "153", name: "Huyện Cao Phong" }, { code: "154", name: "Huyện Tân Lạc" },
    { code: "155", name: "Huyện Mai Châu" }, { code: "156", name: "Huyện Lạc Sơn" },
    { code: "157", name: "Huyện Yên Thủy" }, { code: "158", name: "Huyện Lạc Thủy" },
  ]},
  { code: "19", name: "Thái Nguyên", districts: [
    { code: "164", name: "Thành phố Thái Nguyên" }, { code: "165", name: "Thành phố Sông Công" },
    { code: "167", name: "Huyện Định Hóa" }, { code: "168", name: "Huyện Phú Lương" },
    { code: "169", name: "Huyện Đồng Hỷ" }, { code: "170", name: "Huyện Võ Nhai" },
    { code: "171", name: "Huyện Đại Từ" }, { code: "172", name: "Thị xã Phổ Yên" },
    { code: "173", name: "Huyện Phú Bình" },
  ]},
  { code: "20", name: "Lạng Sơn", districts: [
    { code: "178", name: "Thành phố Lạng Sơn" }, { code: "180", name: "Huyện Tràng Định" },
    { code: "181", name: "Huyện Bình Gia" }, { code: "182", name: "Huyện Văn Lãng" },
    { code: "183", name: "Huyện Cao Lộc" }, { code: "184", name: "Huyện Văn Quan" },
    { code: "185", name: "Huyện Bắc Sơn" }, { code: "186", name: "Huyện Hữu Lũng" },
    { code: "187", name: "Huyện Chi Lăng" }, { code: "188", name: "Huyện Lộc Bình" },
    { code: "189", name: "Huyện Đình Lập" },
  ]},
  { code: "22", name: "Quảng Ninh", districts: [
    { code: "193", name: "Thành phố Hạ Long" }, { code: "194", name: "Thành phố Cam Phả" },
    { code: "195", name: "Thành phố Uông Bí" }, { code: "196", name: "Thành phố Móng Cái" },
    { code: "198", name: "Thị xã Đông Triều" }, { code: "199", name: "Thị xã Quảng Yên" },
    { code: "200", name: "Huyện Bình Liêu" }, { code: "201", name: "Huyện Tiên Yên" },
    { code: "202", name: "Huyện Đầm Hà" }, { code: "203", name: "Huyện Hải Hà" },
    { code: "204", name: "Huyện Ba Chẽ" }, { code: "205", name: "Huyện Vân Đồn" },
    { code: "206", name: "Huyện Hoành Bồ" },
  ]},
  { code: "24", name: "Bắc Giang", districts: [
    { code: "213", name: "Thành phố Bắc Giang" }, { code: "215", name: "Huyện Yên Thế" },
    { code: "216", name: "Huyện Tân Yên" }, { code: "217", name: "Huyện Lạng Giang" },
    { code: "218", name: "Huyện Lục Nam" }, { code: "219", name: "Huyện Lục Ngạn" },
    { code: "220", name: "Huyện Sơn Động" }, { code: "221", name: "Huyện Yên Dũng" },
    { code: "222", name: "Huyện Việt Yên" }, { code: "223", name: "Huyện Hiệp Hòa" },
  ]},
  { code: "25", name: "Phú Thọ", districts: [
    { code: "227", name: "Thành phố Việt Trì" }, { code: "228", name: "Thị xã Phú Thọ" },
    { code: "230", name: "Huyện Đoan Hùng" }, { code: "231", name: "Huyện Hạ Hòa" },
    { code: "232", name: "Huyện Thanh Ba" }, { code: "233", name: "Huyện Phù Ninh" },
    { code: "234", name: "Huyện Yên Lập" }, { code: "235", name: "Huyện Cẩm Khê" },
    { code: "236", name: "Huyện Tam Nông" }, { code: "237", name: "Huyện Lâm Thao" },
    { code: "238", name: "Huyện Thanh Sơn" }, { code: "239", name: "Huyện Thanh Thủy" },
    { code: "240", name: "Huyện Tân Sơn" },
  ]},
  { code: "26", name: "Vĩnh Phúc", districts: [
    { code: "243", name: "Thành phố Vĩnh Yên" }, { code: "244", name: "Thành phố Phúc Yên" },
    { code: "246", name: "Huyện Lập Thạch" }, { code: "247", name: "Huyện Tam Dương" },
    { code: "248", name: "Huyện Tam Đảo" }, { code: "249", name: "Huyện Bình Xuyên" },
    { code: "250", name: "Huyện Vĩnh Tường" }, { code: "251", name: "Huyện Yên Lạc" },
    { code: "252", name: "Huyện Sông Lô" },
  ]},
  { code: "27", name: "Bắc Ninh", districts: [
    { code: "256", name: "Thành phố Bắc Ninh" }, { code: "258", name: "Huyện Yên Phong" },
    { code: "259", name: "Thị xã Quế Võ" }, { code: "260", name: "Huyện Tiên Du" },
    { code: "261", name: "Thị xã Từ Sơn" }, { code: "262", name: "Huyện Thuận Thành" },
    { code: "263", name: "Huyện Gia Bình" }, { code: "264", name: "Huyện Lương Tài" },
  ]},
  { code: "30", name: "Hải Dương", districts: [
    { code: "288", name: "Thành phố Hải Dương" }, { code: "290", name: "Thành phố Chí Linh" },
    { code: "291", name: "Huyện Nam Sách" }, { code: "292", name: "Thị xã Kinh Môn" },
    { code: "293", name: "Huyện Kim Thành" }, { code: "294", name: "Huyện Thanh Hà" },
    { code: "295", name: "Huyện Cẩm Giàng" }, { code: "296", name: "Huyện Bình Giang" },
    { code: "297", name: "Huyện Gia Lộc" }, { code: "298", name: "Huyện Tứ Kỳ" },
    { code: "299", name: "Huyện Ninh Giang" }, { code: "300", name: "Huyện Thanh Miện" },
  ]},
  { code: "31", name: "Hải Phòng", districts: [
    { code: "303", name: "Quận Hồng Bàng" }, { code: "304", name: "Quận Ngô Quyền" },
    { code: "305", name: "Quận Lê Chân" }, { code: "306", name: "Quận Hải An" },
    { code: "307", name: "Quận Kiến An" }, { code: "308", name: "Quận Đồ Sơn" },
    { code: "309", name: "Quận Dương Kinh" }, { code: "311", name: "Huyện Thuỷ Nguyên" },
    { code: "312", name: "Huyện An Dương" }, { code: "313", name: "Huyện An Lão" },
    { code: "314", name: "Huyện Kiến Thuỵ" }, { code: "315", name: "Huyện Tiên Lãng" },
    { code: "316", name: "Huyện Vĩnh Bảo" }, { code: "317", name: "Huyện Cát Hải" },
    { code: "318", name: "Huyện Bạch Long Vĩ" },
  ]},
  { code: "33", name: "Hưng Yên", districts: [
    { code: "323", name: "Thành phố Hưng Yên" }, { code: "325", name: "Huyện Văn Lâm" },
    { code: "326", name: "Huyện Văn Giang" }, { code: "327", name: "Huyện Yên Mỹ" },
    { code: "328", name: "Huyện Mỹ Hào" }, { code: "329", name: "Huyện Ân Thi" },
    { code: "330", name: "Huyện Khoái Châu" }, { code: "331", name: "Huyện Kim Động" },
    { code: "332", name: "Huyện Tiên Lữ" }, { code: "333", name: "Huyện Phù Cừ" },
  ]},
  { code: "34", name: "Thái Bình", districts: [
    { code: "336", name: "Thành phố Thái Bình" }, { code: "338", name: "Huyện Quỳnh Phụ" },
    { code: "339", name: "Huyện Hưng Hà" }, { code: "340", name: "Huyện Đông Hưng" },
    { code: "341", name: "Huyện Thái Thụy" }, { code: "342", name: "Huyện Tiền Hải" },
    { code: "343", name: "Huyện Kiến Xương" }, { code: "344", name: "Huyện Vũ Thư" },
  ]},
  { code: "35", name: "Hà Nam", districts: [
    { code: "347", name: "Thành phố Phủ Lý" }, { code: "349", name: "Thị xã Duy Tiên" },
    { code: "350", name: "Huyện Kim Bảng" }, { code: "351", name: "Huyện Thanh Liêm" },
    { code: "352", name: "Huyện Bình Lục" }, { code: "353", name: "Huyện Lý Nhân" },
  ]},
  { code: "36", name: "Nam Định", districts: [
    { code: "356", name: "Thành phố Nam Định" }, { code: "358", name: "Huyện Mỹ Lộc" },
    { code: "359", name: "Huyện Vụ Bản" }, { code: "360", name: "Huyện Ý Yên" },
    { code: "361", name: "Huyện Nghĩa Hưng" }, { code: "362", name: "Huyện Nam Trực" },
    { code: "363", name: "Huyện Trực Ninh" }, { code: "364", name: "Huyện Xuân Trường" },
    { code: "365", name: "Huyện Giao Thủy" }, { code: "366", name: "Huyện Hải Hậu" },
  ]},
  { code: "37", name: "Ninh Bình", districts: [
    { code: "369", name: "Thành phố Ninh Bình" }, { code: "370", name: "Thành phố Tam Điệp" },
    { code: "372", name: "Huyện Nho Quan" }, { code: "373", name: "Huyện Gia Viễn" },
    { code: "374", name: "Huyện Hoa Lư" }, { code: "375", name: "Huyện Yên Khánh" },
    { code: "376", name: "Huyện Kim Sơn" }, { code: "377", name: "Huyện Yên Mô" },
  ]},
  { code: "38", name: "Thanh Hoá", districts: [
    { code: "380", name: "Thành phố Thanh Hóa" }, { code: "381", name: "Thị xã Bỉm Sơn" },
    { code: "382", name: "Thành phố Sầm Sơn" }, { code: "384", name: "Huyện Mường Lát" },
    { code: "385", name: "Huyện Quan Hóa" }, { code: "386", name: "Huyện Bá Thước" },
    { code: "387", name: "Huyện Quan Sơn" }, { code: "388", name: "Huyện Lang Chánh" },
    { code: "389", name: "Huyện Ngọc Lặc" }, { code: "390", name: "Huyện Cẩm Thủy" },
    { code: "391", name: "Huyện Thạch Thành" }, { code: "392", name: "Huyện Hà Trung" },
    { code: "393", name: "Huyện Vĩnh Lộc" }, { code: "394", name: "Huyện Yên Định" },
    { code: "395", name: "Huyện Thọ Xuân" }, { code: "396", name: "Huyện Thường Xuân" },
    { code: "397", name: "Huyện Triệu Sơn" }, { code: "398", name: "Huyện Thiệu Hóa" },
    { code: "399", name: "Huyện Hoằng Hóa" }, { code: "400", name: "Huyện Hậu Lộc" },
    { code: "401", name: "Huyện Nga Sơn" }, { code: "402", name: "Huyện Như Xuân" },
    { code: "403", name: "Huyện Như Thanh" }, { code: "404", name: "Huyện Nông Cống" },
    { code: "405", name: "Huyện Đông Sơn" }, { code: "406", name: "Huyện Quảng Xương" },
    { code: "407", name: "Thị xã Nghi Sơn" },
  ]},
  { code: "40", name: "Nghệ An", districts: [
    { code: "412", name: "Thành phố Vinh" }, { code: "413", name: "Thị xã Cửa Lò" },
    { code: "414", name: "Thị xã Thái Hòa" }, { code: "415", name: "Huyện Quỳ Châu" },
    { code: "416", name: "Huyện Kỳ Sơn" }, { code: "417", name: "Huyện Tương Dương" },
    { code: "418", name: "Huyện Nghĩa Đàn" }, { code: "419", name: "Huyện Quỳ Hợp" },
    { code: "420", name: "Huyện Quỳnh Lưu" }, { code: "421", name: "Huyện Con Cuông" },
    { code: "422", name: "Huyện Tân Kỳ" }, { code: "423", name: "Huyện Anh Sơn" },
    { code: "424", name: "Huyện Diễn Châu" }, { code: "425", name: "Huyện Yên Thành" },
    { code: "426", name: "Huyện Đô Lương" }, { code: "427", name: "Huyện Thanh Chương" },
    { code: "428", name: "Huyện Nghi Lộc" }, { code: "429", name: "Huyện Nam Đàn" },
    { code: "430", name: "Huyện Hưng Nguyên" }, { code: "431", name: "Thị xã Hoàng Mai" },
  ]},
  { code: "42", name: "Hà Tĩnh", districts: [
    { code: "436", name: "Thành phố Hà Tĩnh" }, { code: "437", name: "Thị xã Hồng Lĩnh" },
    { code: "439", name: "Huyện Hương Sơn" }, { code: "440", name: "Huyện Đức Thọ" },
    { code: "441", name: "Huyện Vũ Quang" }, { code: "442", name: "Huyện Nghi Xuân" },
    { code: "443", name: "Huyện Can Lộc" }, { code: "444", name: "Huyện Hương Khê" },
    { code: "445", name: "Huyện Thạch Hà" }, { code: "446", name: "Huyện Cẩm Xuyên" },
    { code: "447", name: "Huyện Kỳ Anh" }, { code: "448", name: "Thị xã Kỳ Anh" },
  ]},
  { code: "44", name: "Quảng Bình", districts: [
    { code: "450", name: "Thành phố Đồng Hới" }, { code: "452", name: "Huyện Minh Hóa" },
    { code: "453", name: "Huyện Tuyên Hóa" }, { code: "454", name: "Huyện Quảng Trạch" },
    { code: "455", name: "Huyện Bố Trạch" }, { code: "456", name: "Huyện Quảng Ninh" },
    { code: "457", name: "Huyện Lệ Thủy" }, { code: "458", name: "Thị xã Ba Đồn" },
  ]},
  { code: "45", name: "Quảng Trị", districts: [
    { code: "461", name: "Thành phố Đông Hà" }, { code: "462", name: "Thị xã Quảng Trị" },
    { code: "464", name: "Huyện Vĩnh Linh" }, { code: "465", name: "Huyện Hướng Hóa" },
    { code: "466", name: "Huyện Gio Linh" }, { code: "467", name: "Huyện Đa Krông" },
    { code: "468", name: "Huyện Cam Lộ" }, { code: "469", name: "Huyện Triệu Phong" },
    { code: "470", name: "Huyện Hải Lăng" }, { code: "471", name: "Huyện Cồn Cỏ" },
  ]},
  { code: "46", name: "Thừa Thiên Huế", districts: [
    { code: "474", name: "Thành phố Huế" }, { code: "476", name: "Huyện Phong Điền" },
    { code: "477", name: "Huyện Quảng Điền" }, { code: "478", name: "Huyện Phú Vang" },
    { code: "479", name: "Thị xã Hương Thủy" }, { code: "480", name: "Thị xã Hương Trà" },
    { code: "481", name: "Huyện A Lưới" }, { code: "482", name: "Huyện Phú Lộc" },
    { code: "483", name: "Huyện Nam Đông" },
  ]},
  { code: "48", name: "Đà Nẵng", districts: [
    { code: "490", name: "Quận Hải Châu" }, { code: "491", name: "Quận Cẩm Lệ" },
    { code: "492", name: "Quận Liên Chiểu" }, { code: "493", name: "Quận Ngũ Hành Sơn" },
    { code: "494", name: "Quận Sơn Trà" }, { code: "495", name: "Quận Thanh Khê" },
    { code: "497", name: "Huyện Hòa Vang" }, { code: "498", name: "Huyện Hoàng Sa" },
  ]},
  { code: "49", name: "Quảng Nam", districts: [
    { code: "502", name: "Thành phố Tam Kỳ" }, { code: "503", name: "Thành phố Hội An" },
    { code: "504", name: "Huyện Tây Giang" }, { code: "505", name: "Huyện Đông Giang" },
    { code: "506", name: "Huyện Đại Lộc" }, { code: "507", name: "Thị xã Điện Bàn" },
    { code: "508", name: "Huyện Duy Xuyên" }, { code: "509", name: "Huyện Quế Sơn" },
    { code: "510", name: "Huyện Nam Giang" }, { code: "511", name: "Huyện Phước Sơn" },
    { code: "512", name: "Huyện Hiệp Đức" }, { code: "513", name: "Huyện Thăng Bình" },
    { code: "514", name: "Huyện Tiên Phước" }, { code: "515", name: "Huyện Bắc Trà My" },
    { code: "516", name: "Huyện Nam Trà My" }, { code: "517", name: "Huyện Núi Thành" },
    { code: "518", name: "Huyện Phú Ninh" }, { code: "519", name: "Huyện Nông Sơn" },
  ]},
  { code: "51", name: "Quảng Ngãi", districts: [
    { code: "522", name: "Thành phố Quảng Ngãi" }, { code: "524", name: "Huyện Bình Sơn" },
    { code: "525", name: "Huyện Trà Bồng" }, { code: "527", name: "Huyện Sơn Tịnh" },
    { code: "528", name: "Huyện Tư Nghĩa" }, { code: "529", name: "Huyện Sơn Hà" },
    { code: "530", name: "Huyện Sơn Tây" }, { code: "531", name: "Huyện Minh Long" },
    { code: "532", name: "Huyện Nghĩa Hành" }, { code: "533", name: "Huyện Mộ Đức" },
    { code: "534", name: "Huyện Đức Phổ" }, { code: "535", name: "Huyện Ba Tơ" },
    { code: "536", name: "Huyện Lý Sơn" },
  ]},
  { code: "52", name: "Bình Định", districts: [
    { code: "540", name: "Thành phố Quy Nhơn" }, { code: "542", name: "Huyện An Lão" },
    { code: "543", name: "Thị xã Hoài Nhơn" }, { code: "544", name: "Huyện Hoài Ân" },
    { code: "545", name: "Huyện Phù Mỹ" }, { code: "546", name: "Huyện Vĩnh Thạnh" },
    { code: "547", name: "Huyện Tây Sơn" }, { code: "548", name: "Huyện Phù Cát" },
    { code: "549", name: "Thị xã An Nhơn" }, { code: "550", name: "Huyện Tuy Phước" },
    { code: "551", name: "Huyện Vân Canh" },
  ]},
  { code: "54", name: "Phú Yên", districts: [
    { code: "555", name: "Thành phố Tuy Hòa" }, { code: "557", name: "Thị xã Sông Cầu" },
    { code: "558", name: "Huyện Đồng Xuân" }, { code: "559", name: "Huyện Tuy An" },
    { code: "560", name: "Huyện Sơn Hòa" }, { code: "561", name: "Huyện Sông Hinh" },
    { code: "562", name: "Huyện Tây Hòa" }, { code: "563", name: "Huyện Phú Hòa" },
    { code: "564", name: "Thị xã Đông Hòa" },
  ]},
  { code: "56", name: "Khánh Hoà", districts: [
    { code: "568", name: "Thành phố Nha Trang" }, { code: "569", name: "Thành phố Cam Ranh" },
    { code: "570", name: "Huyện Cam Lâm" }, { code: "571", name: "Huyện Vạn Ninh" },
    { code: "572", name: "Huyện Diên Khánh" }, { code: "573", name: "Huyện Khánh Vĩnh" },
    { code: "574", name: "Huyện Khánh Sơn" }, { code: "575", name: "Thị xã Ninh Hòa" },
    { code: "576", name: "Huyện Trường Sa" },
  ]},
  { code: "58", name: "Ninh Thuận", districts: [
    { code: "582", name: "Thành phố Phan Rang-Tháp Chàm" }, { code: "584", name: "Huyện Bác Ái" },
    { code: "585", name: "Huyện Ninh Sơn" }, { code: "586", name: "Huyện Ninh Hải" },
    { code: "587", name: "Huyện Ninh Phước" }, { code: "588", name: "Huyện Thuận Bắc" },
    { code: "589", name: "Huyện Thuận Nam" },
  ]},
  { code: "60", name: "Bình Thuận", districts: [
    { code: "593", name: "Thành phố Phan Thiết" }, { code: "594", name: "Thị xã La Gi" },
    { code: "595", name: "Huyện Tuy Phong" }, { code: "596", name: "Huyện Bắc Bình" },
    { code: "597", name: "Huyện Hàm Thuận Bắc" }, { code: "598", name: "Huyện Hàm Thuận Nam" },
    { code: "599", name: "Huyện Tánh Linh" }, { code: "600", name: "Huyện Đức Linh" },
    { code: "601", name: "Huyện Hàm Tân" }, { code: "602", name: "Huyện Phú Quí" },
  ]},
  { code: "62", name: "Kon Tum", districts: [
    { code: "608", name: "Thành phố Kon Tum" }, { code: "610", name: "Huyện Đắk Glei" },
    { code: "611", name: "Huyện Ngọc Hồi" }, { code: "612", name: "Huyện Đắk Tô" },
    { code: "613", name: "Huyện Kon Plông" }, { code: "614", name: "Huyện Kon Rẫy" },
    { code: "615", name: "Huyện Đắk Hà" }, { code: "616", name: "Huyện Sa Thầy" },
    { code: "617", name: "Huyện Tu Mơ Rông" }, { code: "618", name: "Huyện Ia H'Drai" },
  ]},
  { code: "64", name: "Gia Lai", districts: [
    { code: "622", name: "Thành phố Pleiku" }, { code: "623", name: "Thị xã An Khê" },
    { code: "624", name: "Thị xã Ayun Pa" }, { code: "625", name: "Huyện KBang" },
    { code: "626", name: "Huyện Đăk Đoa" }, { code: "627", name: "Huyện Chư Păh" },
    { code: "628", name: "Huyện Ia Grai" }, { code: "629", name: "Huyện Mang Yang" },
    { code: "630", name: "Huyện Kông Chro" }, { code: "631", name: "Huyện Đức Cơ" },
    { code: "632", name: "Huyện Chư Prông" }, { code: "633", name: "Huyện Chư Sê" },
    { code: "634", name: "Huyện Đăk Pơ" }, { code: "635", name: "Huyện Ia Pa" },
    { code: "637", name: "Huyện Krông Pa" }, { code: "638", name: "Huyện Phú Thiện" },
    { code: "639", name: "Huyện Chư Pưh" },
  ]},
  { code: "66", name: "Đắk Lắk", districts: [
    { code: "643", name: "Thành phố Buôn Ma Thuột" }, { code: "644", name: "Thị xã Buôn Hồ" },
    { code: "645", name: "Huyện Ea H'leo" }, { code: "646", name: "Huyện Ea Súp" },
    { code: "647", name: "Huyện Buôn Đôn" }, { code: "648", name: "Huyện Cư M'gar" },
    { code: "649", name: "Huyện Krông Búk" }, { code: "650", name: "Huyện Krông Năng" },
    { code: "651", name: "Huyện Ea Kar" }, { code: "652", name: "Huyện M'Đrắk" },
    { code: "653", name: "Huyện Krông Bông" }, { code: "654", name: "Huyện Krông Pắc" },
    { code: "655", name: "Huyện Krông A Na" }, { code: "656", name: "Huyện Lắk" },
    { code: "657", name: "Huyện Cư Kuin" },
  ]},
  { code: "67", name: "Đắk Nông", districts: [
    { code: "660", name: "Thành phố Gia Nghĩa" }, { code: "661", name: "Huyện Đăk Glong" },
    { code: "662", name: "Huyện Cư Jút" }, { code: "663", name: "Huyện Đắk Mil" },
    { code: "664", name: "Huyện Krông Nô" }, { code: "665", name: "Huyện Đắk Song" },
    { code: "666", name: "Huyện Đắk R'Lấp" }, { code: "667", name: "Huyện Tuy Đức" },
  ]},
  { code: "68", name: "Lâm Đồng", districts: [
    { code: "672", name: "Thành phố Đà Lạt" }, { code: "673", name: "Thành phố Bảo Lộc" },
    { code: "674", name: "Huyện Đam Rông" }, { code: "675", name: "Huyện Lạc Dương" },
    { code: "676", name: "Huyện Lâm Hà" }, { code: "677", name: "Huyện Đơn Dương" },
    { code: "678", name: "Huyện Đức Trọng" }, { code: "679", name: "Huyện Di Linh" },
    { code: "680", name: "Huyện Bảo Lâm" }, { code: "681", name: "Huyện Đạ Huoai" },
    { code: "682", name: "Huyện Đạ Tẻh" }, { code: "683", name: "Huyện Cát Tiên" },
  ]},
  { code: "70", name: "Bình Phước", districts: [
    { code: "688", name: "Thành phố Đồng Xoài" }, { code: "689", name: "Thị xã Bình Long" },
    { code: "690", name: "Thị xã Phước Long" }, { code: "691", name: "Huyện Bù Gia Mập" },
    { code: "692", name: "Huyện Lộc Ninh" }, { code: "693", name: "Huyện Bù Đốp" },
    { code: "694", name: "Huyện Hớn Quản" }, { code: "695", name: "Huyện Đồng Phú" },
    { code: "696", name: "Huyện Bù Đăng" }, { code: "697", name: "Huyện Chơn Thành" },
    { code: "698", name: "Huyện Phú Riềng" },
  ]},
  { code: "72", name: "Tây Ninh", districts: [
    { code: "703", name: "Thành phố Tây Ninh" }, { code: "705", name: "Huyện Tân Biên" },
    { code: "706", name: "Huyện Tân Châu" }, { code: "707", name: "Huyện Dương Minh Châu" },
    { code: "708", name: "Huyện Châu Thành" }, { code: "709", name: "Huyện Hòa Thành" },
    { code: "710", name: "Huyện Gò Dầu" }, { code: "711", name: "Huyện Bến Cầu" },
    { code: "712", name: "Thị xã Trảng Bàng" },
  ]},
  { code: "74", name: "Bình Dương", districts: [
    { code: "718", name: "Thành phố Thủ Dầu Một" }, { code: "719", name: "Thành phố Thuận An" },
    { code: "720", name: "Thành phố Dĩ An" }, { code: "721", name: "Thành phố Bến Cát" },
    { code: "722", name: "Thành phố Tân Uyên" }, { code: "723", name: "Huyện Bàu Bàng" },
    { code: "724", name: "Huyện Dầu Tiếng" }, { code: "725", name: "Huyện Phú Giáo" },
    { code: "726", name: "Huyện Bắc Tân Uyên" },
  ]},
  { code: "75", name: "Đồng Nai", districts: [
    { code: "731", name: "Thành phố Biên Hòa" }, { code: "732", name: "Thành phố Long Khánh" },
    { code: "734", name: "Huyện Tân Phú" }, { code: "735", name: "Huyện Vĩnh Cửu" },
    { code: "736", name: "Huyện Định Quán" }, { code: "737", name: "Huyện Trảng Bom" },
    { code: "738", name: "Huyện Thống Nhất" }, { code: "739", name: "Huyện Cẩm Mỹ" },
    { code: "740", name: "Huyện Long Thành" }, { code: "741", name: "Huyện Xuân Lộc" },
    { code: "742", name: "Huyện Nhơn Trạch" },
  ]},
  { code: "77", name: "Bà Rịa - Vũng Tàu", districts: [
    { code: "747", name: "Thành phố Vũng Tàu" }, { code: "748", name: "Thành phố Bà Rịa" },
    { code: "750", name: "Huyện Châu Đức" }, { code: "751", name: "Huyện Xuyên Mộc" },
    { code: "752", name: "Huyện Long Điền" }, { code: "753", name: "Huyện Đất Đỏ" },
    { code: "754", name: "Thị xã Phú Mỹ" }, { code: "755", name: "Huyện Côn Đảo" },
  ]},
  { code: "79", name: "TP. Hồ Chí Minh", districts: [
    { code: "760", name: "Quận 1" }, { code: "761", name: "Quận 3" },
    { code: "762", name: "Quận 4" }, { code: "763", name: "Quận 5" },
    { code: "764", name: "Quận 6" }, { code: "765", name: "Quận 7" },
    { code: "766", name: "Quận 8" }, { code: "767", name: "Quận 10" },
    { code: "768", name: "Quận 11" }, { code: "769", name: "Quận 12" },
    { code: "770", name: "Quận Bình Thạnh" }, { code: "771", name: "Quận Gò Vấp" },
    { code: "772", name: "Quận Phú Nhuận" }, { code: "773", name: "Quận Tân Bình" },
    { code: "774", name: "Quận Tân Phú" }, { code: "775", name: "TP. Thủ Đức" },
    { code: "776", name: "Huyện Bình Chánh" }, { code: "777", name: "Huyện Cần Giờ" },
    { code: "778", name: "Huyện Củ Chi" }, { code: "779", name: "Huyện Hóc Môn" },
    { code: "780", name: "Huyện Nhà Bè" },
  ]},
  { code: "80", name: "Long An", districts: [
    { code: "794", name: "Thành phố Tân An" }, { code: "795", name: "Thị xã Kiến Tường" },
    { code: "796", name: "Huyện Tân Hưng" }, { code: "797", name: "Huyện Vĩnh Hưng" },
    { code: "798", name: "Huyện Mộc Hóa" }, { code: "799", name: "Huyện Tân Thạnh" },
    { code: "800", name: "Huyện Thạnh Hóa" }, { code: "801", name: "Huyện Đức Huệ" },
    { code: "802", name: "Huyện Đức Hòa" }, { code: "803", name: "Huyện Bến Lức" },
    { code: "804", name: "Huyện Thủ Thừa" }, { code: "805", name: "Huyện Tân Trụ" },
    { code: "806", name: "Huyện Cần Đước" }, { code: "807", name: "Huyện Cần Giuộc" },
    { code: "808", name: "Huyện Châu Thành" },
  ]},
  { code: "82", name: "Tiền Giang", districts: [
    { code: "815", name: "Thành phố Mỹ Tho" }, { code: "816", name: "Thị xã Gò Công" },
    { code: "817", name: "Thị xã Cai Lậy" }, { code: "818", name: "Huyện Tân Phước" },
    { code: "819", name: "Huyện Cái Bè" }, { code: "820", name: "Huyện Cai Lậy" },
    { code: "821", name: "Huyện Châu Thành" }, { code: "822", name: "Huyện Chợ Gạo" },
    { code: "823", name: "Huyện Gò Công Tây" }, { code: "824", name: "Huyện Gò Công Đông" },
    { code: "825", name: "Huyện Tân Phú Đông" },
  ]},
  { code: "83", name: "Bến Tre", districts: [
    { code: "829", name: "Thành phố Bến Tre" }, { code: "831", name: "Huyện Châu Thành" },
    { code: "832", name: "Huyện Chợ Lách" }, { code: "833", name: "Huyện Mỏ Cày Nam" },
    { code: "834", name: "Huyện Giồng Trôm" }, { code: "835", name: "Huyện Bình Đại" },
    { code: "836", name: "Huyện Ba Tri" }, { code: "837", name: "Huyện Thạnh Phú" },
    { code: "838", name: "Huyện Mỏ Cày Bắc" },
  ]},
  { code: "84", name: "Trà Vinh", districts: [
    { code: "842", name: "Thành phố Trà Vinh" }, { code: "844", name: "Huyện Càng Long" },
    { code: "845", name: "Huyện Cầu Kè" }, { code: "846", name: "Huyện Tiểu Cần" },
    { code: "847", name: "Huyện Châu Thành" }, { code: "848", name: "Huyện Cầu Ngang" },
    { code: "849", name: "Huyện Trà Cú" }, { code: "850", name: "Huyện Duyên Hải" },
    { code: "851", name: "Thị xã Duyên Hải" },
  ]},
  { code: "86", name: "Vĩnh Long", districts: [
    { code: "855", name: "Thành phố Vĩnh Long" }, { code: "857", name: "Huyện Long Hồ" },
    { code: "858", name: "Huyện Mang Thít" }, { code: "859", name: "Huyện Vũng Liêm" },
    { code: "860", name: "Huyện Tam Bình" }, { code: "861", name: "Thị xã Bình Minh" },
    { code: "862", name: "Huyện Trà Ôn" }, { code: "863", name: "Huyện Bình Tân" },
  ]},
  { code: "87", name: "Đồng Tháp", districts: [
    { code: "866", name: "Thành phố Cao Lãnh" }, { code: "867", name: "Thành phố Sa Đéc" },
    { code: "868", name: "Thành phố Hồng Ngự" }, { code: "869", name: "Huyện Tân Hồng" },
    { code: "870", name: "Huyện Hồng Ngự" }, { code: "871", name: "Huyện Tam Nông" },
    { code: "872", name: "Huyện Tháp Mười" }, { code: "873", name: "Huyện Cao Lãnh" },
    { code: "874", name: "Huyện Thanh Bình" }, { code: "875", name: "Huyện Lấp Vò" },
    { code: "876", name: "Huyện Lai Vung" }, { code: "877", name: "Huyện Châu Thành" },
  ]},
  { code: "89", name: "An Giang", districts: [
    { code: "883", name: "Thành phố Long Xuyên" }, { code: "884", name: "Thành phố Châu Đốc" },
    { code: "886", name: "Huyện An Phú" }, { code: "887", name: "Thị xã Tân Châu" },
    { code: "888", name: "Huyện Phú Tân" }, { code: "889", name: "Huyện Châu Phú" },
    { code: "890", name: "Huyện Tịnh Biên" }, { code: "891", name: "Huyện Tri Tôn" },
    { code: "892", name: "Huyện Châu Thành" }, { code: "893", name: "Huyện Chợ Mới" },
    { code: "894", name: "Huyện Thoại Sơn" },
  ]},
  { code: "91", name: "Kiên Giang", districts: [
    { code: "899", name: "Thành phố Rạch Giá" }, { code: "900", name: "Thành phố Hà Tiên" },
    { code: "902", name: "Huyện Kiên Lương" }, { code: "903", name: "Huyện Hòn Đất" },
    { code: "904", name: "Huyện Tân Hiệp" }, { code: "905", name: "Huyện Châu Thành" },
    { code: "906", name: "Huyện Giồng Riềng" }, { code: "907", name: "Huyện Gò Quao" },
    { code: "908", name: "Huyện An Biên" }, { code: "909", name: "Huyện An Minh" },
    { code: "910", name: "Huyện Vĩnh Thuận" }, { code: "911", name: "Thành phố Phú Quốc" },
    { code: "912", name: "Huyện Kiên Hải" }, { code: "913", name: "Huyện U Minh Thượng" },
    { code: "914", name: "Huyện Giang Thành" },
  ]},
  { code: "92", name: "Cần Thơ", districts: [
    { code: "916", name: "Quận Ninh Kiều" }, { code: "917", name: "Quận Ô Môn" },
    { code: "918", name: "Quận Bình Thuỷ" }, { code: "919", name: "Quận Cái Răng" },
    { code: "923", name: "Quận Thốt Nốt" }, { code: "924", name: "Huyện Vĩnh Thạnh" },
    { code: "925", name: "Huyện Cờ Đỏ" }, { code: "926", name: "Huyện Phong Điền" },
    { code: "927", name: "Huyện Thới Lai" },
  ]},
  { code: "93", name: "Hậu Giang", districts: [
    { code: "930", name: "Thành phố Vị Thanh" }, { code: "931", name: "Thành phố Ngã Bảy" },
    { code: "932", name: "Huyện Châu Thành A" }, { code: "933", name: "Huyện Châu Thành" },
    { code: "934", name: "Huyện Phụng Hiệp" }, { code: "935", name: "Huyện Vị Thuỷ" },
    { code: "936", name: "Huyện Long Mỹ" }, { code: "937", name: "Thị xã Long Mỹ" },
  ]},
  { code: "94", name: "Sóc Trăng", districts: [
    { code: "941", name: "Thành phố Sóc Trăng" }, { code: "942", name: "Huyện Châu Thành" },
    { code: "943", name: "Huyện Kế Sách" }, { code: "944", name: "Huyện Mỹ Tú" },
    { code: "945", name: "Huyện Cù Lao Dung" }, { code: "946", name: "Huyện Long Phú" },
    { code: "947", name: "Huyện Mỹ Xuyên" }, { code: "948", name: "Thị xã Ngã Năm" },
    { code: "949", name: "Huyện Thạnh Trị" }, { code: "950", name: "Thị xã Vĩnh Châu" },
    { code: "951", name: "Huyện Trần Đề" },
  ]},
  { code: "95", name: "Bạc Liêu", districts: [
    { code: "954", name: "Thành phố Bạc Liêu" }, { code: "956", name: "Huyện Hồng Dân" },
    { code: "957", name: "Huyện Phước Long" }, { code: "958", name: "Huyện Vĩnh Lợi" },
    { code: "959", name: "Thị xã Giá Rai" }, { code: "960", name: "Huyện Đông Hải" },
    { code: "961", name: "Huyện Hoà Bình" },
  ]},
  { code: "96", name: "Cà Mau", districts: [
    { code: "964", name: "Thành phố Cà Mau" }, { code: "966", name: "Huyện U Minh" },
    { code: "967", name: "Huyện Thới Bình" }, { code: "968", name: "Huyện Trần Văn Thời" },
    { code: "969", name: "Huyện Cái Nước" }, { code: "970", name: "Huyện Đầm Dơi" },
    { code: "971", name: "Huyện Năm Căn" }, { code: "972", name: "Huyện Phú Tân" },
    { code: "973", name: "Huyện Ngọc Hiển" },
  ]},
];
