import { chromium } from '@playwright/test';
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1366, height: 700 } });
await p.goto('http://localhost:3055/', { waitUntil: 'networkidle', timeout: 120000 });
await p.locator('header a', { hasText: 'TẤT CẢ SẢN PHẨM' }).first().hover();
await p.waitForFunction(() => { const d=document.querySelector('[data-dropdown]'); return d && getComputedStyle(d).opacity==='1'; }, { timeout: 10000 });
await p.locator('[data-dropdown] nav button', { hasText: 'Phụ kiện khác' }).first().hover();
await p.waitForTimeout(300);
await p.screenshot({ path: '.artifacts/menu-width/menu-phukien.png' });
console.log('saved');
await b.close();
