-- V1014 (dev-only): Đồng bộ nội dung trang Liên hệ (/lien-he) từ dữ liệu thật trên VPS.
--
-- Vì sao cần: các ô liên hệ (số điện thoại, địa chỉ, email, giờ mở cửa, Zalo…) đã được
-- sửa tay qua admin trên VPS, KHÁC với giá trị seed gốc (V22/V150/V224). Migration này
-- chụp lại trạng thái hiện tại để bản chạy local hiển thị y hệt web thật.
--
-- Phạm vi: CHỈ chạy ở profile dev (thư mục migration-dev) → KHÔNG ảnh hưởng web production
-- (production vốn đã có sẵn dữ liệu này). Tất cả đều idempotent (ON CONFLICT DO UPDATE),
-- chạy lại nhiều lần an toàn. Ảnh/icon trong bố cục dùng asset theme nội bộ, không có media ngoài.
--
-- Nguồn: site_settings(group=contact, 13 ô).
-- Lưu ý: bảng `pages` đã bị gỡ ở V271 (module Pages loại bỏ, 10 trang tĩnh gồm /lien-he nay
-- đóng cứng trong bigbike-web). Vì vậy migration này CHỈ đồng bộ site_settings, không đụng pages.

-- 13 o noi dung nhom contact (so DT, dia chi, email, gio, social)
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'contact_address','79/30/52 Âu Cơ, Phường Hoà Bình, TP. Hồ Chí Minh','79/30/52 Au Co, Ward 14, District 11, Ho Chi Minh City','contact','t','Dia chi cua hang.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'contact_email','bigbikevnshop@gmail.com',NULL,'contact','t','Email lien he cong khai.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'facebook_url','https://www.facebook.com/bigbikegear',NULL,'contact','t','Link Facebook.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'hotline','0906 902 404 ',NULL,'contact','t','Hotline chinh.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'hotline_2','0764 640 679 - Mrs. Thư / Zalo','0764 640 679 - Mrs. Thu / Zalo','contact','t','Hotline phu.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'hotline_3','',NULL,'contact','t','Third hotline number displayed in the footer.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'messenger_display','Bigbike.vn',NULL,'contact','t','Display text for the Messenger line in the floating chat popup.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'messenger_url','https://m.me/bigbikegear',NULL,'contact','t','Facebook Messenger deep link.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'opening_hours_holiday','Lễ / Tết: nghỉ có thông báo','Holidays / Tet: Closed','contact','t','Lịch nghỉ lễ / Tết.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'opening_hours_weekday','T2 - T7: 09h00 - 21h00','Mon - Fri: 09:00 - 21:00','contact','t','Giờ mở cửa thứ 2–thứ 6.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'opening_hours_weekend','CN: 09h00 - 18h00','Sat / Sun: 09:00 - 18:00','contact','t','Giờ mở cửa thứ 7 / Chủ nhật.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'zalo_display','0764640679',NULL,'contact','t','Display text for the Zalo line in the floating chat popup.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'zalo_url','https://zalo.me/84764640679',NULL,'contact','t','Link Zalo.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
