-- V1014 (dev-only): Đồng bộ nội dung trang Liên hệ (/lien-he) từ dữ liệu thật trên VPS.
--
-- Vì sao cần: các ô liên hệ (số điện thoại, địa chỉ, email, giờ mở cửa, Zalo…) đã được
-- sửa tay qua admin trên VPS, KHÁC với giá trị seed gốc (V22/V150/V224). Migration này
-- chụp lại trạng thái hiện tại để bản chạy local hiển thị y hệt web thật.
--
-- Phạm vi: CHỈ chạy ở profile dev (thư mục migration-dev) → KHÔNG ảnh hưởng web production
-- (production vốn đã có sẵn dữ liệu này). Tất cả đều idempotent (ON CONFLICT DO UPDATE),
-- chạy lại nhiều lần an toàn. Ảnh/icon trong bố cục dùng asset theme nội bộ, không có media ngoài.
--
-- Nguồn: pages(slug=lien-he) + site_settings(group=contact, 13 ô).

-- 1) Dong trang lien-he trong bang pages
INSERT INTO pages (id,slug,title,body,page_type,publish_status,seo_title,seo_description,seo_canonical_url,seo_og_image_id,seo_og_image_url,seo_og_image_alt,seo_og_image_width,seo_og_image_height,seo_og_image_mime_type,published_at,created_at,updated_at,parent_id,hero_image_url,hero_image_alt,hero_title,hero_description,hero_kicker,title_en,body_en,hero_title_en,hero_description_en,hero_kicker_en,seo_title_en,seo_description_en,body_blocks) VALUES ('page_lien_he','lien-he','Liên hệ - Shop bảo hộ Bigbike.vn','<div class="desc">
<p><strong>Shop bảo hộ Bigbike.vn</strong> là shop bảo hộ tại TP.HCM, hoạt động từ năm 2014, có website <a href="https://bigbike.vn">bigbike.vn</a>, email <a href="mailto:bigbikevnshop@gmail.com">bigbikevnshop@gmail.com</a>, hotline chính <strong>028 6279 7251</strong>, Zalo <strong>0764 640 679 - Mrs. Thư</strong> và số phụ <strong>0906 902 404 - Mr. Trí</strong> để liên hệ.</p>
</div>
<div class="contact-me">&nbsp;</div>','CONTACT','PUBLISHED',NULL,NULL,'https://bigbike.vn/lien-he/',NULL,NULL,NULL,NULL,NULL,NULL,'2026-04-01 01:00:00+00','2026-04-01 01:00:00+00','2026-06-11 06:29:51.111369+00',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,E'[{"text": "Địa chỉ cửa hàng", "type": "heading", "level": 2}, {"html": "<p><strong>79/30/52 Âu Cơ, Phường 14, Quận 11, TP.HCM</strong></p>", "type": "paragraph"}, {"text": "Hotline & Zalo", "type": "heading", "level": 2}, {"type": "list", "items": ["028.62797251 — Tổng đài", "0764640679 — Mrs. Thư (Zalo)", "0906902404 — Mr. Trí"], "style": "bulleted"}, {"text": "Giờ mở cửa", "type": "heading", "level": 2}, {"html": "<table>\\n <thead>\\n  <tr>\\n   <th>Ngày</th>\\n   <th>Giờ</th>\\n  </tr>\\n </thead>\\n <tbody>\\n  <tr>\\n   <td>Thứ 2 — Thứ 6</td>\\n   <td>09:00 — 21:00</td>\\n  </tr>\\n  <tr>\\n   <td>Thứ 7, Chủ Nhật</td>\\n   <td>09:00 — 18:00</td>\\n  </tr>\\n </tbody>\\n</table>", "type": "paragraph"}, {"text": "Kênh mạng xã hội", "type": "heading", "level": 2}, {"type": "list", "items": ["Facebook: facebook.com/bigbikegear", "YouTube: BigBike Vietnam"], "style": "bulleted"}, {"text": "Để lại lời nhắn", "type": "heading", "level": 2}, {"html": "<p>Nếu bạn cần tư vấn ngoài giờ làm việc, hãy nhắn tin qua <strong>Zalo 0764640679</strong> — chúng tôi sẽ phản hồi sớm nhất có thể.</p>", "type": "paragraph"}]') ON CONFLICT (id) DO UPDATE SET slug=EXCLUDED.slug,title=EXCLUDED.title,body=EXCLUDED.body,page_type=EXCLUDED.page_type,publish_status=EXCLUDED.publish_status,seo_title=EXCLUDED.seo_title,seo_description=EXCLUDED.seo_description,seo_canonical_url=EXCLUDED.seo_canonical_url,seo_og_image_id=EXCLUDED.seo_og_image_id,seo_og_image_url=EXCLUDED.seo_og_image_url,seo_og_image_alt=EXCLUDED.seo_og_image_alt,seo_og_image_width=EXCLUDED.seo_og_image_width,seo_og_image_height=EXCLUDED.seo_og_image_height,seo_og_image_mime_type=EXCLUDED.seo_og_image_mime_type,published_at=EXCLUDED.published_at,updated_at=EXCLUDED.updated_at,parent_id=EXCLUDED.parent_id,hero_image_url=EXCLUDED.hero_image_url,hero_image_alt=EXCLUDED.hero_image_alt,hero_title=EXCLUDED.hero_title,hero_description=EXCLUDED.hero_description,hero_kicker=EXCLUDED.hero_kicker,title_en=EXCLUDED.title_en,body_en=EXCLUDED.body_en,hero_title_en=EXCLUDED.hero_title_en,hero_description_en=EXCLUDED.hero_description_en,hero_kicker_en=EXCLUDED.hero_kicker_en,seo_title_en=EXCLUDED.seo_title_en,seo_description_en=EXCLUDED.seo_description_en,body_blocks=EXCLUDED.body_blocks;

-- 2) 13 o noi dung nhom contact (so DT, dia chi, email, gio, social)
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'contact_address','79/30/52 Âu Cơ, Phường Hoà Bình, TP. Hồ Chí Minh','79/30/52 Au Co, Ward 14, District 11, Ho Chi Minh City','contact','t','Dia chi cua hang.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'contact_email','bigbikevnshop@gmail.com',NULL,'contact','t','Email lien he cong khai.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'facebook_url','https://www.facebook.com/bigbikegear',NULL,'contact','t','Link Facebook.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'hotline','0906 902 404 ',NULL,'contact','t','Hotline chinh.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'hotline_2','0764 640 679 - Mrs. Thư / Zalo','0764 640 679 - Mrs. Thu / Zalo','contact','t','Hotline phu.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'hotline_3','',NULL,'contact','t','Third hotline number displayed in the footer.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'messenger_display','Bigbike.vn',NULL,'contact','t','Display text for the Messenger line in the floating chat popup.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'messenger_url','https://m.me/bigbikegear',NULL,'contact','t','Facebook Messenger deep link.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'opening_hours_holiday','Lễ / Tết: nghỉ có thông báo','Holidays / Tet: Closed','contact','t','Lịch nghỉ lễ / Tết.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'opening_hours_weekday','T2 - T7: 09h00 - 21h00','Mon - Fri: 09:00 - 21:00','contact','t','Giờ mở cửa thứ 2–thứ 6.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'opening_hours_weekend','CN: 09h00 - 18h00','Sat / Sun: 09:00 - 18:00','contact','t','Giờ mở cửa thứ 7 / Chủ nhật.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'zalo_display','0764640679',NULL,'contact','t','Display text for the Zalo line in the floating chat popup.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();
INSERT INTO site_settings (id,setting_key,setting_value,setting_value_en,setting_group,is_public,description,created_at,updated_at) VALUES (gen_random_uuid(),'zalo_url','https://zalo.me/84764640679',NULL,'contact','t','Link Zalo.',now(),now()) ON CONFLICT (setting_key) DO UPDATE SET setting_value=EXCLUDED.setting_value,setting_value_en=EXCLUDED.setting_value_en,setting_group=EXCLUDED.setting_group,is_public=EXCLUDED.is_public,updated_at=now();

