-- brands description_en
UPDATE brands SET description_en = $b$<p>HJC is one of the world's leading manufacturers and distributors of motorcycle helmets. Founded in 1971 in South Korea, HJC quickly became one of the most trusted names in the helmet industry for motorcycles, off-road bikes, and other vehicles.</p>
<p>HJC is renowned for combining innovative design with advanced technology to produce safe, high-quality helmets. The brand always adheres to the highest safety standards and continuously tests to improve its helmets' protective performance.</p>$b$ WHERE id = 'wp-brand-2591';

UPDATE brands SET description_en = $b$<p>Alpinestars is Italy's leading protective gear brand for professional motorcycle racers worldwide. A constant presence in top MotoGP championships and the main sponsor of world number-one rider Marc Márquez, Alpinestars produces riding suits, gloves, and boots that are the top choice for riders at every level.</p>$b$ WHERE id = 'wp-brand-363';

UPDATE brands SET description_en = $b$<p>AGV is a premier racing helmet brand with over 70 years of experience, having become a symbol of safety and quality in motorsport. Designed and manufactured in Italy, each AGV helmet is highly regarded for its technical performance and innovative design. Lightweight materials, excellent ventilation, and an advanced impact-absorption system deliver maximum protection. AGV is also the official sponsor of MotoGP legend Valentino Rossi.</p>$b$ WHERE id = 'wp-brand-364';

UPDATE brands SET description_en = $b$<p>Komine is a renowned manufacturer of motorcycle riding gear and protective equipment. Founded in Japan, Komine has over 70 years of experience producing high-quality products including riding jackets, gloves, boots, and safety accessories. The brand is known for combining innovative design, quality materials, and advanced technology to deliver optimal protection and comfort for motorcycle riders.</p>$b$ WHERE id = 'wp-brand-3704';

UPDATE brands SET description_en = $b$<p>Founded in 1969 by Jacques Segura, Furygan's history has been shaped by a passion for perfection and precision.</p>
<p>In its early days, the company focused on developing and manufacturing gloves for cycling, skiing, and of course motorcycle riding — one of Mr. Jacques' deepest passions.</p>
<p>Today, Furygan is recognized as one of France's leading protective gear brands, trusted by professional and amateur riders alike for quality, innovation, and style.</p>$b$ WHERE id = 'wp-brand-373';

UPDATE brands SET description_en = $b$<p>LS2 is a well-known Spanish brand specializing in manufacturing motorcycle helmets certified to ECE-R and DOT standards. Since 2020, LS2 has also launched a collection of protective riding apparel and gloves under the LS2 brand name.</p>$b$ WHERE id = 'wp-brand-374';

UPDATE brands SET description_en = $b$<p>Scoyco is a brand specializing in the manufacture and sale of protective gear and accessories for motorcycle and bicycle riders. Originating from China, Scoyco has built a reputation for providing quality and safe products to the riding community. Scoyco's range includes riding jackets, gloves, boots, helmets, and other accessories — all designed to deliver the best protection and comfort for riders.</p>$b$ WHERE id = 'wp-brand-375';

UPDATE brands SET description_en = $b$<p>MT Helmets is a well-known motorcycle helmet brand originating from Spain. It has become one of the most trusted names in the personal protective equipment industry. The brand stands out for combining modern design, high quality, and exceptional protective performance, ensuring users can ride safely and confidently.</p>$b$ WHERE id = 'wp-brand-378';

UPDATE brands SET description_en = $b$<p>Helite is a French company specializing in the development and manufacture of personal safety devices. The brand is renowned for producing airbag systems for motorcyclists, cyclists, sports enthusiasts, and medical applications. Helite's technology allows the airbag system to automatically deploy upon a fall or collision, providing an additional layer of protection beyond traditional gear.</p>$b$ WHERE id = 'wp-brand-379';

UPDATE brands SET description_en = $b$<p>It all started from the passion of a racer: TAICHI's founder, Taichi Yoshimura. Drawing on his extensive experience as a top-level racer, he wanted to share the joy of riding with all motorcycle enthusiasts. Their mission is to create products that allow riders to enjoy their motorcycles safely and comfortably. Taichi produces a full range of motorcycle riding gear designed to enhance performance and protection on every journey.</p>$b$ WHERE id = 'wp-brand-380';

UPDATE brands SET description_en = $b$<p>TCX (Touring Club Cross) is a prestigious manufacturer of riding boots and protective footwear for motorcycle riders. Founded in 1999 in Italy, TCX has quickly become one of the leading brands in the motorcycle protection industry. TCX specializes in producing riding boots and footwear, offering safe and comfortable solutions for motorcycle enthusiasts around the world.</p>$b$ WHERE id = 'wp-brand-382';

UPDATE brands SET description_en = $b$<p>GIVI is a renowned brand in the motorcycle accessories segment. Founded in 1978 in Italy, GIVI has become a globally trusted name. The brand is known for providing quality products such as panniers, top cases, windscreens, and other accessories for motorcycles and scooters. The combination of smart design and superior functionality has made GIVI the top choice for motorcycle touring enthusiasts worldwide.</p>$b$ WHERE id = 'wp-brand-383';

UPDATE brands SET description_en = $b$<p>Gaerne is a well-known brand in the manufacture of boots and protective products for motorcycle and bicycle riders. Founded in 1962 in Italy by Ernesto Gazzola, Gaerne has become a familiar name in the riding community thanks to the quality and unique design of its products. Gaerne specializes in producing protective boots combining premium materials with advanced safety technology.</p>$b$ WHERE id = 'wp-brand-3857';

UPDATE brands SET description_en = $b$<p>SW-Motech is a specialist manufacturer and distributor of motorcycle accessories and equipment, based in Germany with over 20 years of industry experience. SW-Motech is known for providing high-quality, elegantly designed products with innovative solutions for motorcyclists. Their range includes luggage systems, crash bars, handguards, quick-lock tankbags, and a wide variety of other accessories.</p>$b$ WHERE id = 'wp-brand-386';

UPDATE brands SET description_en = $b$<p>The SCS story began in 2010, when the entire team dedicated themselves to the motorcycle communication system industry. From the basic 2-rider intercom S7, to the 4-rider S1 & S9 communication devices with FM radio on the S3. With input from the global motorcycle community, SCS invented the S11 — a camera-equipped helmet headset that was a first in the industry.</p>$b$ WHERE id = 'wp-brand-387';

UPDATE brands SET description_en = $b$<p>Sena is a brand built by motorcycle riders and technology enthusiasts alike. Founded in 1998, Sena started as an industrial technology company providing enterprise-grade Bluetooth® networking products to customers worldwide. After long-term success, the Sena team began thinking about other ways technology could help riders stay connected and communicate on the road — leading to the world-renowned Sena Bluetooth headset lineup.</p>$b$ WHERE id = 'wp-brand-388';

UPDATE brands SET description_en = $b$<p>LIQUI MOLY is a German specialist in the production of motor oils, automotive additives, and quality chemicals. With over 60 years of experience, the brand has become one of the leading names in the automotive and engine care industry. LIQUI MOLY is renowned for high-quality products that contribute to engine performance, efficiency, and longevity.</p>$b$ WHERE id = 'wp-brand-390';

UPDATE brands SET description_en = $b$<p>Enduristan is a specialist manufacturer and supplier of high-quality gear and accessories for big-bike riders. With a perfect combination of smart design, durable materials, and outstanding waterproof performance, Enduristan products are reliable and professional in all terrain conditions. From luggage bags and hydration packs to backpacks and waterproof gloves, Enduristan brings convenience and peace of mind to every adventure.</p>$b$ WHERE id = 'wp-brand-3926';

UPDATE brands SET description_en = $b$<p>WE WANT TO LEAVE YOUR FOOTPRINT IN THE MOTORCYCLE WORLD</p>$b$ WHERE id = 'wp-brand-4405';

UPDATE brands SET description_en = $b$<p>"Soluzioni Innovative X lo Sport" — meaning "Innovative Solutions for Sports" — is the acronym and name of SIXS, making it easy to see just how deeply the brand's commitment to innovation and product research runs. The SIXS story began in 2009 in Italy, in Bagnara di Romagna (Province of Ravenna), with a mission to bring cutting-edge technical performance to athletes and riders.</p>$b$ WHERE id = 'wp-brand-4428';

UPDATE brands SET description_en = $b$<p>GSADV was born from a group of young enthusiasts passionate about big-displacement motorcycles. Founded in 2010, GSADV is a motorcycle touring accessory brand focused on independent research and development. They preserve the essence of artisanal craftsmanship in the industry — spanning more than a decade — because they deeply understand the specific needs of professional bikers.</p>$b$ WHERE id = 'wp-brand-4561';

UPDATE brands SET description_en = $b$<p>Nexx is a leading motorcycle helmet brand founded in Portugal that has established a strong presence in the global market. The brand is known for designing and manufacturing innovative helmets in diverse styles and materials. Nexx focuses on balancing safety and style, utilizing advanced technology to deliver the best possible protection for riders at every level.</p>$b$ WHERE id = 'wp-brand-4794';

UPDATE brands SET description_en = $b$<p>For over 40 years, Australian motorcycle protective gear brand DRIRIDER has helped protect riders with high-quality clothing and accessories — riding jackets, boots, gloves, luggage, and helmets. Designed exclusively for two-wheel riders and adapted for the climate conditions in Vietnam.</p>$b$ WHERE id = 'wp-brand-500';

UPDATE brands SET description_en = $b$<p>Richa is a well-known brand in the manufacture and supply of personal protective gear, especially for motorcycle riders. The brand is recognized for combining high quality with modern design across its full product range. Richa's lineup includes riding jackets, gloves, boots, and helmets — all using premium materials and advanced technology to ensure safety and comfort for riders.</p>$b$ WHERE id = 'wp-brand-6071';
