-- Categories name_en
UPDATE categories SET name_en = 'AuditParent'                                  WHERE id = 'cat_aed66e36c56b4899951d16a1d68c4d99';
UPDATE categories SET name_en = 'Leather Jackets & Leather Suits'              WHERE id = 'wp-cat-315';
UPDATE categories SET name_en = 'Textile Riding Jacket'                        WHERE id = 'wp-cat-304';
UPDATE categories SET name_en = 'Airbag Riding Jacket'                         WHERE id = 'wp-cat-307';
UPDATE categories SET name_en = 'Backpack'                                     WHERE id = 'wp-cat-301';
UPDATE categories SET name_en = 'Backpacks, Bags & Bike-Mounted Bags'          WHERE id = 'wp-cat-294';
UPDATE categories SET name_en = 'Boots'                                        WHERE id = 'wp-cat-6291';
UPDATE categories SET name_en = 'Backpacks'                                    WHERE id = 'wp-cat-6517';
UPDATE categories SET name_en = 'Motorcycle Clothing'                          WHERE id = 'wp-cat-6485';
UPDATE categories SET name_en = 'Uncategorized'                                WHERE id = 'wp-cat-359';
UPDATE categories SET name_en = 'Full Face Helmets'                            WHERE id = 'wp-cat-6322';
UPDATE categories SET name_en = 'Protective Footwear'                          WHERE id = 'wp-cat-292';
UPDATE categories SET name_en = 'Body Armor & Accessories'                     WHERE id = 'wp-cat-293';
UPDATE categories SET name_en = 'Gloves'                                       WHERE id = 'wp-cat-291';
UPDATE categories SET name_en = 'Helmets'                                      WHERE id = 'wp-cat-6320';
UPDATE categories SET name_en = 'Kewig'                                        WHERE id = 'wp-cat-6704';
UPDATE categories SET name_en = 'Hot Deals'                                    WHERE id = 'wp-cat-287';
UPDATE categories SET name_en = 'Replacement Visors & Anti-Fog Pinlock'        WHERE id = 'wp-cat-298';
UPDATE categories SET name_en = 'Leather Jackets & Suits'                      WHERE id = 'wp-cat-6489';
UPDATE categories SET name_en = 'Helmets'                                      WHERE id = 'wp-cat-289';
UPDATE categories SET name_en = '3/4 Face Helmets'                             WHERE id = 'wp-cat-318';
UPDATE categories SET name_en = 'Flip-Up Full Face Helmets'                    WHERE id = 'wp-cat-309';
UPDATE categories SET name_en = 'Off-Road & Dual Sport Helmets'                WHERE id = 'wp-cat-325';
UPDATE categories SET name_en = 'Full Face Helmets'                            WHERE id = 'wp-cat-303';
UPDATE categories SET name_en = 'LS2 Full Face Helmets'                        WHERE id = 'wp-cat-6500';
UPDATE categories SET name_en = 'Accessories & Phone Mounts'                   WHERE id = 'wp-cat-311';
UPDATE categories SET name_en = 'Rain Gear & Accessories'                      WHERE id = 'wp-cat-297';
UPDATE categories SET name_en = 'Base Layer Accessories'                       WHERE id = 'wp-cat-305';
UPDATE categories SET name_en = 'Other Accessories'                            WHERE id = 'wp-cat-299';
UPDATE categories SET name_en = 'Quadlock'                                     WHERE id = 'wp-cat-6604';
UPDATE categories SET name_en = 'Underpants'                                   WHERE id = 'wp-cat-4465';
UPDATE categories SET name_en = 'Riding Pants & Armored Pants'                 WHERE id = 'wp-cat-323';
UPDATE categories SET name_en = 'Rok Strap'                                    WHERE id = 'wp-cat-6606';
UPDATE categories SET name_en = 'Soft Bags'                                    WHERE id = 'wp-cat-6515';
UPDATE categories SET name_en = 'Gear Cleaning & Bike Care Products'           WHERE id = 'wp-cat-296';
UPDATE categories SET name_en = 'Bluetooth Headsets'                           WHERE id = 'wp-cat-295';
UPDATE categories SET name_en = 'Textile Jackets'                              WHERE id = 'wp-cat-6487';
UPDATE categories SET name_en = 'Balaclava'                                    WHERE id = 'wp-cat-4469';
UPDATE categories SET name_en = 'Bike-Mounted Bags'                            WHERE id = 'wp-cat-324';
UPDATE categories SET name_en = 'Hip Bags & Waist Bags'                        WHERE id = 'wp-cat-319';
UPDATE categories SET name_en = 'Thigh Bags'                                   WHERE id = 'wp-cat-312';
UPDATE categories SET name_en = 'Uncategorized'                                WHERE id = 'uncategorized';
UPDATE categories SET name_en = 'Socks & Arm Sleeves'                          WHERE id = 'wp-cat-4471';
UPDATE categories SET name_en = 'Base Layer Top'                               WHERE id = 'wp-cat-4467';
UPDATE categories SET name_en = 'Motorcycle Riding Gear'                       WHERE id = 'wp-cat-290';

-- Brands: all names are already in English — copy name → name_en
UPDATE brands SET name_en = name WHERE name_en IS NULL;
