UPDATE home_videos SET title_en = 'KOMINE 265 Gloves'                                          WHERE id = 'hv-wp-00d227ef';
UPDATE home_videos SET title_en = 'Gloves 269'                                                  WHERE id = 'hv-wp-01c011ed';
UPDATE home_videos SET title_en = 'NIC'                                                          WHERE id = 'hv-wp-04048020';
UPDATE home_videos SET title_en = 'KOMINE 269 Gloves'                                           WHERE id = 'hv-wp-0a27f5fe';
UPDATE home_videos SET title_en = 'LS2 RayMan Gloves — What Are All Those Holes Actually Protecting?' WHERE id = 'hv-wp-0a2e8903';
UPDATE home_videos SET title_en = 'Spyke Sahara'                                                WHERE id = 'hv-wp-0bbed331';
UPDATE home_videos SET title_en = 'French Helite Airbag Jacket Deploys at Supersonic Speed — Ultimate Protection for Bikers!' WHERE id = 'hv-wp-198b9474';
UPDATE home_videos SET title_en = 'Ego Balaclava'                                               WHERE id = 'hv-wp-1ebe9976';
UPDATE home_videos SET title_en = 'How to Properly Wear a Full Alpinestars Leather Suit — Tutorial!' WHERE id = 'hv-wp-2206eb62';
UPDATE home_videos SET title_en = 'LS2 OF610'                                                   WHERE id = 'hv-wp-29f632df';
UPDATE home_videos SET title_en = 'SCS S3 Bluetooth Intercom for Full Face Helmet'              WHERE id = 'hv-wp-2f7f1d22';
UPDATE home_videos SET title_en = 'LS2 Dartman Gloves — A Must-Have for BigBike City Riders!'  WHERE id = 'hv-wp-37c07471';
UPDATE home_videos SET title_en = 'Why You Should Install the SCS S-6 Bluetooth Headset on Your 3/4 Helmet' WHERE id = 'hv-wp-42780d7a';
UPDATE home_videos SET title_en = 'How Good Is It? SCS S-9 Bluetooth Intercom Headset for Helmets' WHERE id = 'hv-wp-45186c0f';
UPDATE home_videos SET title_en = 'Forma Low'                                                   WHERE id = 'hv-wp-4703eaa7';
UPDATE home_videos SET title_en = 'Only 690K! SCS S-6 Bluetooth Headset — Does It Meet Your Needs?' WHERE id = 'hv-wp-4f7eb4d5';
UPDATE home_videos SET title_en = 'S12'                                                          WHERE id = 'hv-wp-510b1111';
UPDATE home_videos SET title_en = 'LS2 RustMan Classic Goatskin Moto Gloves — Incredibly Comfortable' WHERE id = 'hv-wp-59e9ab7b';
UPDATE home_videos SET title_en = 'ONeal'                                                        WHERE id = 'hv-wp-5e3db53b';
UPDATE home_videos SET title_en = 'Compass Spyke'                                               WHERE id = 'hv-wp-69c1b627';
UPDATE home_videos SET title_en = 'Biggest Tank Bag for Bigbike Riders — Menat MB018'           WHERE id = 'hv-wp-6b1eafb2';
UPDATE home_videos SET title_en = 'A Legend That Lives On! Premium Sena 10S Bluetooth Headset for Helmets' WHERE id = 'hv-wp-6ba73861';
UPDATE home_videos SET title_en = '10 Million VND Full Face! LS2 FF327 Carbon 2019 — Premium Review' WHERE id = 'hv-wp-7866b235';
UPDATE home_videos SET title_en = 'KOMINE 177'                                                  WHERE id = 'hv-wp-79c46873';
UPDATE home_videos SET title_en = 'S7X'                                                          WHERE id = 'hv-wp-79f6d90e';
UPDATE home_videos SET title_en = 'Testing 4K Video Recording on the Incredible Sena 10C EVO!' WHERE id = 'hv-wp-7ef558ca';
UPDATE home_videos SET title_en = 'Carberg'                                                     WHERE id = 'hv-wp-84582593';
UPDATE home_videos SET title_en = 'Rokstrap Strap'                                              WHERE id = 'hv-wp-89445c1c';
UPDATE home_videos SET title_en = 'SCS S-9 Bluetooth Intercom Headset for Full Face Helmet'    WHERE id = 'hv-wp-90dc7d03';
UPDATE home_videos SET title_en = 'Unrivaled! Sena 30K Bluetooth Intercom'                     WHERE id = 'hv-wp-91d95291';
UPDATE home_videos SET title_en = 'SCS S-6 Installation Guide + Connecting 2 Smartphones & Speaker Test' WHERE id = 'hv-wp-97042736';
UPDATE home_videos SET title_en = 'Fog City'                                                    WHERE id = 'hv-wp-9c730ffd';
UPDATE home_videos SET title_en = 'HJC IS2V'                                                    WHERE id = 'hv-wp-9fe5cf35';
UPDATE home_videos SET title_en = 'RayMan'                                                      WHERE id = 'hv-wp-a13cf3c3';
UPDATE home_videos SET title_en = 'Your Full Face Helmet Is Incomplete Without the Sena 20S Evo' WHERE id = 'hv-wp-a22bbf9b';
UPDATE home_videos SET title_en = 'S9X'                                                          WHERE id = 'hv-wp-a4a5b1b6';
UPDATE home_videos SET title_en = 'SCS S-7 Full Review + Installation + Connecting 2 Smartphones' WHERE id = 'hv-wp-a8930bc5';
UPDATE home_videos SET title_en = 'CUCYMA Tail Bag — Still Intact After a 299 km Ride!'        WHERE id = 'hv-wp-aa3a4d94';
UPDATE home_videos SET title_en = 'REVIEW: Hottest Helmet of 2020 "LS2 FF800" — Ultra-Lightweight KPA Material!' WHERE id = 'hv-wp-aa5a1a72';
UPDATE home_videos SET title_en = 'LS2 SparkMan Gloves — Ready to Race!'                        WHERE id = 'hv-wp-ae926cc9';
UPDATE home_videos SET title_en = 'Dainese Lady'                                                WHERE id = 'hv-wp-af1dd150';
UPDATE home_videos SET title_en = 'How to Install SW Motech Waterproof Bags on Your Bike'      WHERE id = 'hv-wp-b449d66d';
UPDATE home_videos SET title_en = 'Premium Quality at a Great Price! Alpinestars Intertial Air Gloves' WHERE id = 'hv-wp-b7120aae';
UPDATE home_videos SET title_en = 'S8X'                                                          WHERE id = 'hv-wp-ba204c84';
UPDATE home_videos SET title_en = 'Leg Armor 819 690'                                           WHERE id = 'hv-wp-bd462fe9';
UPDATE home_videos SET title_en = 'LS2 Swift Racing Full Leather Moto Gloves — Incredibly Stylish!' WHERE id = 'hv-wp-c0e70393';
UPDATE home_videos SET title_en = 'FF900'                                                        WHERE id = 'hv-wp-c0ea64c4';
UPDATE home_videos SET title_en = 'SCS S-9 Helmet Installation & Connection Guide'              WHERE id = 'hv-wp-c6557515';
UPDATE home_videos SET title_en = 'SMK'                                                          WHERE id = 'hv-wp-cda6d77f';
UPDATE home_videos SET title_en = 'Authentic Alpinestars Axel Air Motorcycle Riding Jacket'     WHERE id = 'hv-wp-d19c05d0';
UPDATE home_videos SET title_en = 'Installing the Givi XS313 Seat Bag — Never Falls Off! Installation Guide' WHERE id = 'hv-wp-d3daf21a';
UPDATE home_videos SET title_en = 'Komine Level 2 Shoulder & Arm Armor'                        WHERE id = 'hv-wp-d5b7e994';
UPDATE home_videos SET title_en = 'SMK Retro'                                                   WHERE id = 'hv-wp-d8833058';
UPDATE home_videos SET title_en = 'RS Taichi 335 Jacket'                                        WHERE id = 'hv-wp-dd977ba6';
UPDATE home_videos SET title_en = 'BMW Raceflow Riding Jacket for Summer'                       WHERE id = 'hv-wp-e0f83d17';
UPDATE home_videos SET title_en = 'How to Connect 4-Rider Intercom with SCS S-9?'              WHERE id = 'hv-wp-f375e72d';
UPDATE home_videos SET title_en = 'SCS S-3: Connect 2 Phones Simultaneously & 4-Way Intercom Guide' WHERE id = 'hv-wp-f5e2df24';
UPDATE home_videos SET title_en = 'Is It Worth It? Sena 10C EVO Bluetooth Intercom with 4K Video Recording' WHERE id = 'hv-wp-fa3c6dcd';
UPDATE home_videos SET title_en = '354'                                                          WHERE id = 'hv-wp-fa4cc07c';
