import { chromium } from "playwright";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 2880, height: 1500 }, deviceScaleFactor: 1 });
await page.goto("http://localhost:3018/product/mu-bao-hiem-fullface-ilm-racing-helmet-mf509/", { waitUntil: "networkidle" });
await page.waitForSelector(".bb-wp-pdp-gallery-col", { timeout: 20000 });
await page.addStyleTag({ content: "*{transition:none!important;animation:none!important;}" });
await page.waitForTimeout(600);
await page.screenshot({ path: ".artifacts/pdp-4xl-align/many-2880.png", clip:{x:0,y:0,width:2880,height:1050} });
await browser.close();
console.log("saved many-2880.png");
