const { chromium } = require("playwright");
const fs = require("fs");
const OUT = ".artifacts/checkout-parity";
const seed = async (p, base) => {
  await p.goto(base + "/", { waitUntil: "networkidle" });
  await p.evaluate(async () => {
    const ck = n => { const m = document.cookie.match(new RegExp("(?:^|; )" + n + "=([^;]*)")); return m ? decodeURIComponent(m[1]) : null; };
    const api = (me, pa, bo) => fetch("http://localhost:8080" + pa, { method: me, headers: { "Content-Type": "application/json", "X-CSRF-Token": ck("bb_csrf") || "" }, credentials: "include", body: bo ? JSON.stringify(bo) : undefined }).then(r => r.status);
    await api("POST", "/api/v1/customer/auth/login", { login: "duc237022@gmail.com", password: "12345678", remember: true });
    await api("DELETE", "/api/v1/cart/clear");
    await api("POST", "/api/v1/cart/items", { productId: "wp-prod-6093", productVariantId: "wp-var-6094", quantity: 1 });
  });
};
const PROBE = () => {
  const out = {};
  const g = (el, ps) => { if (!el) return "MISSING"; const c = getComputedStyle(el); return ps.map(p => p + "=" + c[p]).join("; "); };
  const W = el => el ? Math.round(el.getBoundingClientRect().width) : "MISSING";
  const cont = document.querySelector(".bb-checkout-page");
  const row = document.querySelector(".bb-checkout-content-row");
  const main = document.querySelector(".bb-checkout-content-main");
  const side = document.querySelector(".bb-checkout-content-side");
  out.title = g(document.querySelector(".check-out-title"), ["paddingLeft"]);
  out.titleH1 = g(document.querySelector(".check-out-title h1"), ["fontFamily", "fontSize", "fontWeight", "lineHeight", "textTransform", "color", "margin"]);
  out.row = g(row, ["display", "gridTemplateColumns", "gap", "flexDirection"]);
  out.rowW = W(row); out.mainW = W(main); out.sideW = W(side);
  out.main = g(main, ["minWidth"]);
  out.side = g(side, ["minWidth", "marginTop"]);
  const step = document.querySelector(".check-out-step");
  out.step = g(step, ["border", "borderColor", "background", "padding", "marginBottom", "borderRadius"]);
  out.stepTitle = g(document.querySelector(".check-out-step-title"), ["marginBottom"]);
  const h2 = document.querySelector(".check-out-step-title h2");
  out.stepH2 = g(h2, ["display", "alignItems", "gap", "margin", "fontFamily", "fontSize", "fontWeight", "lineHeight", "textTransform"]);
  out.stepH2span = g(h2 && h2.querySelector("span"), ["display", "width", "height", "flexBasis", "alignItems", "justifyContent", "background", "backgroundColor", "color", "borderRadius", "fontSize"]);
  out.fieldsGrid = g(document.querySelector(".bb-checkout-fields-grid"), ["display", "gridTemplateColumns", "gap"]);
  out.formGroup = g(document.querySelector(".form-group"), ["display", "gridTemplateColumns", "gap", "marginBottom"]);
  out.label = g(document.querySelector(".bb-checkout-content-main label"), ["display", "fontSize", "lineHeight", "fontWeight", "marginBottom", "color"]);
  const fc = document.querySelector(".form-control");
  out.formControl = g(fc, ["width", "height", "minHeight", "border", "borderColor", "borderWidth", "padding", "paddingLeft", "fontSize", "color", "backgroundColor", "borderRadius"]);
  out.addrGrid = g(document.querySelector(".bb-checkout-address-grid"), ["display", "gridTemplateColumns", "gap"]);
  out.orderComments = g(document.querySelector(".bb-order-comments"), ["marginTop"]);
  out.methodBlock = g(document.querySelector(".bb-checkout-method-block"), ["display", "marginTop", "borderTop", "borderTopColor", "paddingTop", "gap"]);
  out.methodH3 = g(document.querySelector(".bb-checkout-method-block h3"), ["margin", "fontFamily", "fontSize", "fontWeight", "textTransform", "lineHeight"]);
  out.radioList = g(document.querySelector(".bb-checkout-radio-list"), ["display", "gap", "gridTemplateColumns"]);
  const rr = document.querySelector(".bb-checkout-radio-row");
  out.radioRow = g(rr, ["display", "minHeight", "alignItems", "gap", "border", "borderColor", "background", "backgroundColor", "padding"]);
  out.radioLabel = g(document.querySelector(".bb-checkout-radio-label"), ["minWidth", "flex", "fontWeight"]);
  out.radioPrice = g(document.querySelector(".bb-checkout-radio-price"), ["color", "fontFamily", "fontWeight", "whiteSpace"]);
  out.payment = g(document.querySelector(".bb-checkout-payment"), ["marginTop", "borderTop", "borderTopColor", "paddingTop"]);
  out.paymentMethods = g(document.querySelector(".wc_payment_methods"), ["display", "gap", "margin", "padding", "listStyleType", "gridTemplateColumns"]);
  out.paymentMethod = g(document.querySelector(".wc_payment_method"), ["margin"]);
  out.paymentLabel = g(document.querySelector(".bb-checkout-payment-label"), ["display", "minHeight", "alignItems", "gap", "border", "borderColor", "padding"]);
  out.placeOrderWrap = g(document.querySelector(".place-order"), ["marginTop"]);
  const submit = document.querySelector('button[type="submit"]');
  out.submitBtn = g(submit, ["width", "minHeight", "fontFamily", "fontSize", "fontWeight", "letterSpacing", "textTransform", "backgroundColor", "color"]);
  out.summary = g(document.querySelector(".checkout-summary"), ["border", "borderColor", "background", "backgroundColor", "padding", "position", "top"]);
  out.summaryTitle = g(document.querySelector(".checkout-summary-title h3"), ["margin", "fontFamily", "fontSize", "fontWeight", "lineHeight", "textTransform", "color"]);
  out.reviewOrder = g(document.querySelector(".woocommerce-checkout-review-order"), ["overflowX"]);
  out.shopTable = g(document.querySelector(".shop_table"), ["minWidth", "width", "borderCollapse"]);
  out.totalSummary = g(document.querySelector(".summary.total-summary"), ["marginTop", "border", "borderColor", "background", "backgroundColor", "padding", "display"]);
  out.totalSummaryItems = g(document.querySelector(".summary.total-summary .summary--items"), ["display", "justifyContent", "gap"]);
  out.totalPrice = g(document.querySelector(".total-price"), ["color", "fontSize", "fontWeight", "margin"]);
  out.summaryPayment = g(document.querySelector(".bb-checkout-summary-payment"), ["marginTop", "border", "borderColor", "background", "backgroundColor", "padding"]);
  return out;
};
(async () => {
  const b = await chromium.launch(); const ctx = await b.newContext(); const p = await ctx.newPage();
  await seed(p, "http://localhost:3000");
  const res = {};
  for (const w of [1280, 390]) {
    await p.setViewportSize({ width: w, height: 1100 });
    await p.goto("http://localhost:3000/thanh-toan/", { waitUntil: "networkidle" });
    await p.waitForSelector("form.checkout", { timeout: 15000 }).catch(() => {});
    await p.waitForTimeout(700);
    res[w] = await p.evaluate(PROBE);
    await p.screenshot({ path: `${OUT}/old-${w}.png`, fullPage: true });
  }
  fs.writeFileSync(`${OUT}/old-computed.json`, JSON.stringify(res, null, 2));
  console.log(JSON.stringify(res, null, 2));
  await b.close();
})();
